In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\Salary Prediction Data\salary_final_data.csv")

In [3]:
df.head()

,Unnamed: 0,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
0,0,Data Analyst,3.5,Gurugram,"['Data Analytics', 'Supply Chain Management', ...",350000.0,0
1,1,Data Analyst,6.0,Hyderabad,"['Data Analytics', 'Python', 'SQL']",1300000.0,0
2,2,Data Analyst,5.5,Hyderabad,"['Power BI', 'Data Analysis', 'Python', 'SQL',...",1200000.0,0
3,3,Data Analyst,4.0,Hyderabad,"['Informatica', 'ETL', 'Data Warehousing', 'Da...",650000.0,0
4,4,Data Analyst,4.0,Hyderabad,"['Informatica', 'ETL', 'Iics']",650000.0,0

In [4]:
df.columns

Index(['Unnamed: 0', 'Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salary_avg', 'remote_status'],
      dtype='object')

In [5]:
df.drop(columns='Unnamed: 0' , axis=1 , inplace = True)

In [6]:
df.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
0,Data Analyst,3.5,Gurugram,"['Data Analytics', 'Supply Chain Management', ...",350000.0,0
1,Data Analyst,6.0,Hyderabad,"['Data Analytics', 'Python', 'SQL']",1300000.0,0
2,Data Analyst,5.5,Hyderabad,"['Power BI', 'Data Analysis', 'Python', 'SQL',...",1200000.0,0
3,Data Analyst,4.0,Hyderabad,"['Informatica', 'ETL', 'Data Warehousing', 'Da...",650000.0,0
4,Data Analyst,4.0,Hyderabad,"['Informatica', 'ETL', 'Iics']",650000.0,0

In [7]:
df.sample(5)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
995,Business Analyst,2.5,Bengaluru,"['.NET', 'SQL', 'Business Analytics', 'Project...",1050000.0,0
394,Data Scientist,1.5,Mumbai,"['Data Science', 'Data Analysis', 'Data Analyt...",400000.0,0
6151,Analytics,4.5,Bengaluru,"['Java', 'Javascript', 'Hibernate', 'Spring', ...",1250000.0,0
7260,Analytics,14.0,Bengaluru,"['Corporate Banking', 'Trade Finance', 'Big Da...",2000000.0,0
8364,Data Analyst,5.5,Bengaluru,"['Excel', 'Statistical Analysis', 'Data Valida...",NaN,0

In [8]:
df.isnull().sum()

Standardized_Job_Title       0
Experience_Years             9
Location                     0
Skills Required              0
salary_avg                1410
remote_status                0
dtype: int64

In [9]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Analytics                    2697
Business Analyst             1842
Data Analyst                 1447
Data Scientist               1394
Data Engineer                1309
Machine Learning Engineer     375
Product Analyst                26
Name: count, dtype: int64

In [10]:
df.shape

(9090, 6)

In [11]:
df= df[df['salary_avg'].notnull()].copy()

In [12]:
df.sample(5)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
6894,Analytics,4.5,Hyderabad,"['Pricing Analysis', 'analytics', 'Business An...",2000000.0,0
3579,Machine Learning Engineer,4.0,Gurgaon,"['Deep Learning', 'Natural Language Processing...",1250000.0,0
1305,Data Analyst,2.0,Mumbai,"['Data Analyst', 'Customer service', 'Credit r...",675000.0,0
7375,Business Analyst,10.0,Pune,"['Requirement Gathering', 'Gap Analysis', 'SCO...",800000.0,0
1991,Data Scientist,3.5,Gurgaon,"['cassandra', 'r', 'sql']",780000.0,0

In [13]:
df.shape

(7680, 6)

In [14]:
df['Skills Required'] = df['Skills Required'].astype(str).str.lower()

In [15]:
type(df['Skills Required'][0])

str

In [16]:
df = df[df['Skills Required'] != '[]']

In [17]:
df.shape

(7649, 6)

In [18]:
df= df[df['Experience_Years'].notnull()].copy()

In [19]:
df.shape

(7640, 6)

In [20]:
import ast

df["Skills Required"] = df["Skills Required"].apply(ast.literal_eval)

In [21]:
df['Skills Required'] = df['Skills Required'].astype(str).str.lower()

In [22]:
type(df['Skills Required'][0])

str

In [23]:
df['Skills Required'] = df['Skills Required'].str.replace('[' , '')
df['Skills Required'] = df['Skills Required'].str.replace(']' , '')

In [24]:
df.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
0,Data Analyst,3.5,Gurugram,"'data analytics', 'supply chain management', '...",350000.0,0
1,Data Analyst,6.0,Hyderabad,"'data analytics', 'python', 'sql'",1300000.0,0
2,Data Analyst,5.5,Hyderabad,"'power bi', 'data analysis', 'python', 'sql', ...",1200000.0,0
3,Data Analyst,4.0,Hyderabad,"'informatica', 'etl', 'data warehousing', 'dat...",650000.0,0
4,Data Analyst,4.0,Hyderabad,"'informatica', 'etl', 'iics'",650000.0,0

In [25]:
df[df.duplicated(keep= False)]

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
101,Data Analyst,2.5,Pune,"'sfdc', 'cloud', 'pdf', 'xml', 'delta', 'web t...",500000.0,0
102,Data Analyst,2.5,Pune,"'sfdc', 'cloud', 'pdf', 'xml', 'delta', 'web t...",500000.0,0
135,Data Analyst,1.0,Pimpri-Chinchwad,"'pimpri-chinchwad', 'pune'",500000.0,0
137,Data Analyst,1.0,Pimpri-Chinchwad,"'pimpri-chinchwad', 'pune'",500000.0,0
139,Data Analyst,2.5,Thane,"'thane', 'navi mumbai', 'mumbai'",350000.0,0
...,...,...,...,...,...,...
7672,Analytics,7.5,Chennai,"'data analytics', 'sql', 'statistics', 'r', 'e...",2000000.0,0
7673,Analytics,13.5,Bengaluru,"'hive', 'hdfs', 'hadoop', 'sqoop', 'mapreduce'...",2000000.0,0
7674,Analytics,1.5,Noida,"'communication skills', 'voice process', 'go g...",800000.0,0
7675,Business Analyst,8.5,Bengaluru,"'hr analytics', 'sql', 'uat', 'cpg', 'business...",1250000.0,0
7679,Analytics,10.5,Bengaluru,"'sales enablement', 'mis', 'business operation...",3750000.0,0

In [26]:
df[df.duplicated()]

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
102,Data Analyst,2.5,Pune,"'sfdc', 'cloud', 'pdf', 'xml', 'delta', 'web t...",500000.0,0
137,Data Analyst,1.0,Pimpri-Chinchwad,"'pimpri-chinchwad', 'pune'",500000.0,0
143,Data Analyst,1.0,Pimpri-Chinchwad,"'pimpri-chinchwad', 'pune'",500000.0,0
161,Data Analyst,1.0,Pimpri-Chinchwad,"'pimpri-chinchwad', 'pune'",500000.0,0
172,Data Analyst,1.0,Pimpri-Chinchwad,"'pimpri-chinchwad', 'pune'",500000.0,0
...,...,...,...,...,...,...
7672,Analytics,7.5,Chennai,"'data analytics', 'sql', 'statistics', 'r', 'e...",2000000.0,0
7673,Analytics,13.5,Bengaluru,"'hive', 'hdfs', 'hadoop', 'sqoop', 'mapreduce'...",2000000.0,0
7674,Analytics,1.5,Noida,"'communication skills', 'voice process', 'go g...",800000.0,0
7675,Business Analyst,8.5,Bengaluru,"'hr analytics', 'sql', 'uat', 'cpg', 'business...",1250000.0,0
7679,Analytics,10.5,Bengaluru,"'sales enablement', 'mis', 'business operation...",3750000.0,0

In [27]:
df.drop_duplicates(keep="first", inplace=True)

In [28]:
df.shape

(6626, 6)

In [29]:
df.sample(5)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
3291,Business Analyst,3.0,Bengaluru,"'r', 'sql'",690000.0,0
4266,Business Analyst,6.5,Hyderabad,"'ehr', 'business analysis', 'us healthcare', '...",450000.0,0
3239,Data Engineer,5.5,Pune,"'aws', 'gcp', 'hadoop', 'java', 'python', 'r',...",580000.0,0
2592,Data Engineer,7.5,Mumbai,"'nosql', 'python', 'r', 'scala', 'spark', 'sql'",1100000.0,0
1999,Data Scientist,3.0,Hyderabad,"'management', 'project', 'r'",780000.0,0

In [30]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Analytics                    1426
Business Analyst             1364
Data Analyst                 1227
Data Scientist               1181
Data Engineer                1142
Machine Learning Engineer     267
Product Analyst                19
Name: count, dtype: int64

In [31]:
df = df[df["Standardized_Job_Title"] != "Product Analyst"]

In [32]:
df[df["Standardized_Job_Title"] == "Analytics"].head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
1191,Analytics,0.0,Remote,"'python', 'sql', 'data analytics', 'ms-excel',...",762500.0,1
1194,Analytics,0.0,Remote,"'python', 'sql', 'data analytics', 'ms-excel',...",600000.0,1
1195,Analytics,0.0,Bangalore,"'python', 'sql', 'data analytics', 'ms-excel',...",575000.0,0
1197,Analytics,0.0,Bangalore,"'python', 'sql', 'data analytics', 'ms-excel',...",550000.0,0
1202,Analytics,0.0,Remote,"'java', 'html', 'css', 'javascript', 'web deve...",500000.0,1

In [33]:
from collections import Counter

for role in df["Standardized_Job_Title"].unique():

    skills_text = " ".join(
        df[df["Standardized_Job_Title"] == role]["Skills Required"]
        .astype(str)
    )

    skills = [
        s.strip()
        for s in skills_text.split(",")
    ]

    top_skills = Counter(skills).most_common(10)

    print(f"\n{role}")
    print(top_skills)

Data Analyst
[("'r'", 178), ("'data analysis'", 176), ("'sql'", 169), ("'python'", 149), ("'excel'", 89), ("'data analytics'", 87), ("'tableau'", 54), ("'data visualization'", 43), ("'machine learning'", 42), ("'data mining'", 40)]

Data Scientist
[("'python'", 441), ("'machine learning'", 399), ("'r'", 303), ("'sql'", 127), ("'r' 'machine learning'", 91), ("'nlp'", 84), ("'java'", 76), ("'data science'", 65), ("'spark'", 59), ("'deep learning'", 55)]

Data Engineer
[("'r'", 408), ("'python'", 370), ("'etl'", 181), ("'spark'", 175), ("'sql'", 159), ("'scala'", 141), ("'hadoop'", 130), ("'java'", 127), ("'big data'", 86), ("'nosql'", 84)]

Machine Learning Engineer
[("'machine learning'", 139), ("'python'", 92), ("'r'", 40), ("'c++'", 33), ("'java'", 32), ("'nlp'", 29), ("'data mining'", 26), ("'sql'", 21), ("'natural language processing'", 19), ("'analytics'", 19)]

Business Analyst
[("'business analysis'", 302), ("'sql'", 94), ("'r'", 67), ("'agile'", 60), ("'project management'", 57), ("'brd'", 54), ("'requirement gathering'", 51), ("'analytics'", 48), ("'python'", 44), ("'user stories'", 42)]

Analytics
[("'sas'", 201), ("'analytics'", 197), ("'r'", 179), ("'sql'", 120), ("'python'", 96), ("'data analytics'", 83), ("'machine learning'", 83), ("'data analysis'", 60), ("'excel'", 54), ("'tableau'", 47)]

In [34]:
df.groupby(
    "Standardized_Job_Title"
)["salary_avg"].agg(
    ["mean", "median", "min", "max"]
)

                                   mean     median       min         max
Standardized_Job_Title
Analytics                  1.432846e+06  1250000.0  150000.0   3750000.0
Business Analyst           1.053279e+06   800000.0  100000.0   5000000.0
Data Analyst               8.432302e+05   500000.0   60000.0  15750000.0
Data Engineer              8.710123e+05   580000.0  150000.0   4500000.0
Data Scientist             1.301632e+06   800000.0   50000.0  11250000.0
Machine Learning Engineer  1.624045e+06  1250000.0  150000.0   4650000.0

In [35]:
df = df.copy()

In [36]:
import re


# ============================================
# SKILL STANDARDIZATION MAPPING
# ============================================

SKILL_MAPPING = {

    # Programming Languages
    "py": "python",
    "python3": "python",
    "r": "r programming",
    "r language": "r programming",
    "c++": "cpp",
    "c plus plus": "cpp",
    "js": "javascript",

    # Machine Learning / AI
    "ml": "machine learning",
    "dl": "deep learning",
    "nlp": "natural language processing",
    "ai": "artificial intelligence",

    # Databases
    "postgres": "postgresql",
    "postgre": "postgresql",
    "mongo": "mongodb",

    # Cloud
    "aws cloud": "aws",
    "amazon web services": "aws",
    "gcp": "google cloud platform",

    # Visualization
    "powerbi": "power bi",
    "ms excel": "excel",
    "microsoft excel": "excel",

    # Big Data
    "hdfs": "hadoop",
}


# ============================================
# CLEAN SINGLE SKILL
# ============================================

def clean_single_skill(skill):
    """
    Clean and standardize one skill token.

    Parameters:
        skill (str)

    Returns:
        str
    """

    if pd.isna(skill):
        return ""

    # lowercase
    skill = str(skill).lower().strip()

    # remove quotes
    skill = skill.replace("'", "")
    skill = skill.replace('"', "")

    # remove extra spaces
    skill = re.sub(r"\s+", " ", skill)

    # remove special characters except +
    skill = re.sub(r"[^a-zA-Z0-9+# ]", "", skill)

    # apply mapping
    skill = SKILL_MAPPING.get(skill, skill)

    return skill


# ============================================
# CLEAN COMPLETE SKILL STRING
# ============================================

def clean_skills(skills_text):
    """
    Clean complete skills column.

    Parameters:
        skills_text (str)

    Returns:
        str
    """

    if pd.isna(skills_text):
        return ""

    # lowercase
    skills_text = str(skills_text).lower()

    # split skills
    raw_skills = re.split(r",|\||/|;", skills_text)

    cleaned_skills = []

    for skill in raw_skills:

        cleaned_skill = clean_single_skill(skill)

        # skip empty tokens
        if cleaned_skill == "":
            continue

        # skip very short noisy tokens
        if len(cleaned_skill) <= 1:
            continue

        cleaned_skills.append(cleaned_skill)

    # remove duplicates
    cleaned_skills = list(set(cleaned_skills))

    # sort for consistency
    cleaned_skills.sort()

    # convert back to string
    return ", ".join(cleaned_skills)


# ============================================
# APPLY TO DATAFRAME
# ============================================

df["Skills Required"] = df["Skills Required"].apply(clean_skills)

In [37]:
df["Standardized_Job_Title"] = df[
    "Standardized_Job_Title"
].replace({
    "Analytics": "Analytics Specialist"
})

In [38]:
df.sample(5)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
2816,Data Engineer,2.5,Gurugram,"cassandra, mongodb, python, r programming, redis",580000.0,0
7203,Data Analyst,2.0,Bengaluru,"data analytics, data analysis, data visualiza...",450000.0,0
1094,Business Analyst,3.5,Mumbai,"business analysis, business analytics, power b...",550000.0,0
2122,Data Scientist,7.5,Chennai,"cassandra, cpp, r programming",780000.0,0
2243,Data Engineer,9.5,Serilingampally,"nosql, oracle, r programming, sql",1100000.0,0

In [39]:
df.duplicated(
    subset=[
        "Standardized_Job_Title",
        "salary_avg",
        "Experience_Years",
        "Location",
        "Skills Required"
    ]
).sum()

np.int64(5)

In [40]:
df.shape

(6607, 6)

In [41]:
df.drop_duplicates(
    subset=[
        "Standardized_Job_Title",
        "salary_avg",
        "Experience_Years",
        "Location",
        "Skills Required"
    ]
 , inplace= True)

In [42]:
df.shape

(6602, 6)

In [43]:
df["Experience_Years"].describe()

count    6602.000000
mean        5.797334
std         3.058681
min         0.000000
25%         3.500000
50%         5.500000
75%         7.500000
max        23.000000
Name: Experience_Years, dtype: float64

In [44]:
df["Experience_Years"].value_counts().sort_index()

Experience_Years
0.0      47
0.5      52
1.0      76
1.5     118
2.0     235
2.5     301
3.0     442
3.5     588
4.0     429
4.5     565
5.0     348
5.5     545
6.0     316
6.5     474
7.0     164
7.5     558
8.0     120
8.5     235
9.0      90
9.5     219
10.0    136
10.5    158
11.0     39
11.5     37
12.0     23
12.5     97
13.0     20
13.5     25
14.0     35
14.5     11
15.0     44
15.5      9
16.0     11
16.5      4
17.0      3
17.5      8
18.0      3
18.5      5
19.0      1
20.0      7
20.5      1
21.5      1
22.5      1
23.0      1
Name: count, dtype: int64

In [45]:
df["salary_avg"].describe(percentiles=[0.90, 0.95, 0.99])

count    6.602000e+03
mean     1.131998e+06
std      8.552953e+05
min      5.000000e+04
50%      8.000000e+05
90%      2.000000e+06
95%      3.004750e+06
99%      3.750000e+06
max      1.575000e+07
Name: salary_avg, dtype: float64

In [46]:
all_skills = []

for row in df["Skills Required"]:
    all_skills.extend(row.split(","))

from collections import Counter

Counter(
    [s.strip() for s in all_skills]
).most_common(30)

[('r programming', 2430),
 ('python', 1570),
 ('sql', 1395),
 ('machine learning', 1187),
 ('business analysis', 652),
 ('data analysis', 597),
 ('analytics', 593),
 ('sas', 485),
 ('spark', 445),
 ('java', 435),
 ('management', 400),
 ('data analytics', 395),
 ('tableau', 367),
 ('excel', 366),
 ('hadoop', 336),
 ('aws', 334),
 ('etl', 300),
 ('data science', 283),
 ('natural language processing', 252),
 ('scala', 249),
 ('data mining', 237),
 ('deep learning', 235),
 ('agile', 230),
 ('power bi', 222),
 ('big data', 205),
 ('data engineering', 177),
 ('azure', 175),
 ('project management', 172),
 ('nosql', 171),
 ('data modeling', 158)]

In [47]:
df.isnull().sum()

Standardized_Job_Title    0
Experience_Years          0
Location                  0
Skills Required           0
salary_avg                0
remote_status             0
dtype: int64

In [48]:
df.groupby(
    "Standardized_Job_Title"
)["Experience_Years"].describe()

,count,mean,std,min,25%,50%,75%,max
Standardized_Job_Title,,,,,,,,
Analytics Specialist,1423.0,7.084680,3.712842,0.0,4.0,6.5,9.5,21.5
Business Analyst,1363.0,5.390315,2.968304,0.0,3.5,5.0,7.5,18.5
Data Analyst,1227.0,4.576202,2.605776,0.0,3.0,4.0,6.0,18.0
Data Engineer,1142.0,5.650613,2.340456,0.0,3.5,5.5,7.5,17.5
Data Scientist,1181.0,5.989839,2.696573,0.0,4.0,5.5,7.5,23.0
Machine Learning Engineer,266.0,6.404135,3.020562,1.0,4.0,6.5,7.5,17.5

In [49]:
df.groupby(
    "Standardized_Job_Title"
)["salary_avg"].describe()

,count,mean,std,min,25%,50%,75%,max
Standardized_Job_Title,,,,,,,,
Analytics Specialist,1423.0,1.432704e+06,9.859013e+05,150000.0,800000.0,1250000.0,2000000.0,3750000.0
Business Analyst,1363.0,1.053942e+06,7.270280e+05,100000.0,650000.0,800000.0,1250000.0,5000000.0
Data Analyst,1227.0,8.432302e+05,7.944018e+05,60000.0,470000.0,500000.0,1000000.0,15750000.0
Data Engineer,1142.0,8.710123e+05,5.571252e+05,150000.0,580000.0,580000.0,1100000.0,4500000.0
Data Scientist,1181.0,1.301632e+06,8.568382e+05,50000.0,780000.0,800000.0,1890000.0,11250000.0
Machine Learning Engineer,266.0,1.622632e+06,1.094520e+06,150000.0,800000.0,1250000.0,2000000.0,4650000.0

In [50]:
df["Location"].nunique()

110

In [51]:
df["Location"].value_counts().head(20)

Location
Bengaluru     1947
Mumbai         857
Hyderabad      623
Pune           608
Chennai        464
Gurgaon        445
Delhi NCR      413
Noida          241
Gurugram       222
Kolkata        100
Remote          75
Ahmedabad       58
Delhi           56
Kochi           49
Mohali          30
Jaipur          27
Indore          24
Nagpur          21
Trivandrum      21
Chandigarh      19
Name: count, dtype: int64

In [52]:
df.corr(numeric_only=True)

                  Experience_Years  salary_avg  remote_status
Experience_Years          1.000000     0.51464      -0.078649
salary_avg                0.514640     1.00000      -0.033740
remote_status            -0.078649    -0.03374       1.000000

In [53]:
df.isnull().sum()

Standardized_Job_Title    0
Experience_Years          0
Location                  0
Skills Required           0
salary_avg                0
remote_status             0
dtype: int64

In [54]:
df.shape

(6602, 6)

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Analytics Specialist         1423
Business Analyst             1363
Data Analyst                 1227
Data Scientist               1181
Data Engineer                1142
Machine Learning Engineer     266
Name: count, dtype: int64

In [57]:
df.remote_status.value_counts()

remote_status
0    6527
1      75
Name: count, dtype: int64

In [58]:
df.isnull().sum(
    
)

Standardized_Job_Title    0
Experience_Years          0
Location                  0
Skills Required           0
salary_avg                0
remote_status             0
dtype: int64

In [ ]:
df.to_csv(r"d:/Startup/Project/ai-career-coach/data/Salary Prediction Data/salary_cleaned_data.csv" , index=False)

In [60]:
df

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
0,Data Analyst,3.5,Gurugram,"analytics, data analytics, data governance, da...",350000.0,0
1,Data Analyst,6.0,Hyderabad,"data analytics, python, sql",1300000.0,0
2,Data Analyst,5.5,Hyderabad,"data analysis, power bi, python, sql, tableau",1200000.0,0
3,Data Analyst,4.0,Hyderabad,"data integration, data modeling, data pipeline...",650000.0,0
4,Data Analyst,4.0,Hyderabad,"etl, iics, informatica",650000.0,0
...,...,...,...,...,...,...
7667,Data Analyst,2.5,Pune,"data analysis, data analytics, excel, predicti...",450000.0,0
7669,Data Engineer,7.5,EU,"cassandra, elastic search, hadoop, hive, java,...",2000000.0,0
7676,Business Analyst,4.5,Gurgaon,"analytics, big data, machine learning",1250000.0,0
7677,Data Scientist,9.0,Mumbai,"big data analytics, neural networks, predictiv...",2000000.0,0
7678,Analytics Specialist,5.0,Bengaluru,"advanced analytics, data analysis, data analyt...",1250000.0,0

In [61]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salary_avg', 'remote_status'],
      dtype='object')

In [62]:
df.dtypes

Standardized_Job_Title     object
Experience_Years          float64
Location                   object
Skills Required            object
salary_avg                float64
remote_status               int64
dtype: object