In [130]:
import pandas as pd

In [131]:
data = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\processed\salary_jobs.csv')

In [132]:
data.columns

Index(['Job Title', 'Company Name', 'Location', 'Experience Required',
       'Salary', 'Skills Required', 'Job Description', 'Posted Date',
       'Scrape Date', 'Job Link', 'Source Platform', 'Standardized_Job_Title',
       'days_sinced_posted', 'salary_min', 'salary_max', 'salary_avg',
       'Experience_Years'],
      dtype='object')

In [133]:
df = data[['Standardized_Job_Title' , 'Experience_Years' , 'Location' , 'Skills Required' 
           , 'Company Name' , 'Source Platform' , 'salary_avg']]

In [134]:
df.shape

(75, 7)

In [135]:
df

,Standardized_Job_Title,Experience_Years,Location,Skills Required,Company Name,Source Platform,salary_avg
0,Data Analyst,0.0,Remote,"['English Proficiency (Spoken)', 'English Prof...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
1,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
2,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
3,Data Analyst,0.0,Remote,['Data Analysis'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
4,Data Analyst,0.0,Remote,"['Urdu Proficiency(Spoken)', 'Urdu Proficiency...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
...,...,...,...,...,...,...,...
70,Data Analyst,1.0,Hyderabad,"['Python', 'SQL', 'Statistical Modeling', 'Dat...",DECCAN FOUNDERS MEDIA PVT LTD,Internshala,240000.0
71,Business Analyst,1.0,Kolkata,"['UI & UX Design', 'Technical Analysis', 'Busi...",The Jain Group,Internshala,300000.0
72,Analytics,1.0,Delhi,"['Data Analytics', 'MS-Excel']",Growify Digital,Internshala,250000.0
73,Data Analyst,1.0,Delhi,"['Python', 'SQL', 'Statistical Modeling', 'Bus...",Avadeti Media (Part Of Ojas Group),Internshala,250000.0
74,Business Analyst,0.0,Bangalore,"['MS-Office', 'Planning', 'MS-Excel', 'Busines...",Mobillor Technologies Private Limited,Internshala,225000.0

In [136]:
def remote_status(location):
    if r'Remote' in location:
        return 1
    else:
        return 0

In [137]:
df =df.copy()

In [138]:
df['remote_status'] = df['Location'].apply(remote_status)

In [139]:
df.remote_status.value_counts()

remote_status
1    44
0    31
Name: count, dtype: int64

In [140]:
df.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,Company Name,Source Platform,salary_avg,remote_status
0,Data Analyst,0.0,Remote,"['English Proficiency (Spoken)', 'English Prof...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
1,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
2,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
3,Data Analyst,0.0,Remote,['Data Analysis'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
4,Data Analyst,0.0,Remote,"['Urdu Proficiency(Spoken)', 'Urdu Proficiency...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1

In [141]:
data2 = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\Salary Prediction Data\dataAnalystJobsIndia.csv')

In [142]:
data2.head()

,Unnamed: 0,job_title,company,experience,min exp,max exp,salary,base salary,max salary,location,jobListed(days ago),postedIn,rating,reviews count,details,salary data provide by
0,0,JP Morgan Chase - Client Data Analyst (4-8 yrs),JP Morgan Chase,4-8 Yrs,4.0,8.0,NaN,NaN,NaN,Hyderabad / Secunderabad,3.0,iimjobs,4.1,5300.0,"Banking, KYC, Banking Operations",NaN
1,1,Data Analyst - Bangalore,Schneider Electric,5-10 Yrs,5.0,10.0,₹ 8 - 16L/yr,800000.0,1600000.0,"Bangalore / Bengaluru, Bangalore Rural",4.0,Naukri,4.2,3500.0,"ERP, SAP, Data Analysis",Salary Listed by Company
2,2,Senior IT ATLAS Data Analyst and Integration S...,SAP Labs India Pvt. Ltd.,7-11 Yrs,7.0,11.0,NaN,NaN,NaN,Bangalore / Bengaluru,7.0,Naukri,4.3,1500.0,"data quality, Data analysis, quality management",NaN
3,3,Consultant Data Analyst,Pfizer,2-6 Yrs,2.0,6.0,NaN,NaN,NaN,Mumbai,3.0,Naukri,4.1,1700.0,"Power Bi, Commercial Operations, Data Management",NaN
4,4,Senior Data Analyst - Retail Liabilities,IDFC FIRST Bank,5-10 Yrs,5.0,10.0,NaN,NaN,NaN,Mumbai,5.0,Naukri,4.5,2300.0,"Test strategy, Analytical, Manager Technology",NaN

In [143]:
data2.isnull().sum()

Unnamed: 0                   0
job_title                    0
company                      0
experience                  34
min exp                     34
max exp                     34
salary                    1218
base salary               1218
max salary                1218
location                    33
jobListed(days ago)          0
postedIn                     0
rating                     437
reviews count              437
details                     33
salary data provide by    1218
dtype: int64

In [144]:
data2 = data2[data2['base salary'].notnull()].copy()
data2.reset_index(drop=True , inplace=True)

In [145]:
data2.shape

(343, 16)

In [146]:
def standardize_job_title(title):
    title = str(title).lower()

    if "data analyst" in title:
        return "Data Analyst"
    elif "data scientist" in title:
        return "Data Scientist"
    elif "business analyst" in title:
        return "Business Analyst"
    elif "machine learning" in title:
        return "Machine Learning Engineer"
    elif "data engineer" in title:
        return "Data Engineer"
    elif "product analyst" in title:
        return "Product Analyst"
    elif "analytics" in title:
        return "Analytics"
    else:
        return "Other"

In [147]:

data2['Standardize_Job_Title'] = data2['job_title'].apply(standardize_job_title)

location cleaning

In [148]:
import re

In [149]:
def clean_location(location):

    if pd.isna(location):
        return "Unknown"

    location = str(location)

    # remove +more
    location = re.sub(r"\+.*more", "", location)

    # remove tabs/newlines
    location = re.sub(r"\s+", " ", location).strip()

    # split multi-city
    location = location.split(",")[0].strip()

    # mapping
    location_map = {

        "Bangalore / Bengaluru": "Bengaluru",
        "Bengaluru/Bangalore": "Bengaluru",
        "Bangalore Rural": "Bengaluru",
        "Bangalore/Bengaluru": "Bengaluru",

        "Mohali/SAS Nagar" : "Mohali" ,

        "Trivandrum/Thiruvananthapuram" : "Thiruvananthapuram" ,

        "Delhi/Ncr": "Delhi NCR",
        "New Delhi": "Delhi NCR",
        "Delhi / NCR": "Delhi NCR",

        "Gurgaon / Gurugram": "Gurugram",
        "Gurgaon/Gurugram": "Gurugram",

        "Mumbai suburbs": "Mumbai",
        "Mumbai Suburbs": "Mumbai",
        "Navi Mumbai": "Mumbai",

        "Hyderabad / Secunderabad": "Hyderabad",
        "Hyderabad/Secunderabad": "Hyderabad",

        "Mangaluru/Mangalore" : "Mangalore" , 

        "Panaji/Panjim" : "Panaji" ,

        "Calicut/Kozhikode" : "Calicut" , 

        "Kochi/Cochin" : "Kochi" ,
        "Cochin/Ernakulam/Kochi" : "Kochi",

        "Remote": "Remote",

        "India": "Remote"
    }

    return location_map.get(location, location)

In [150]:
data2["standard_location"] = data2["location"].apply(clean_location)

In [151]:
data2.standard_location.value_counts()

standard_location
Bengaluru                72
Mumbai                   48
Chennai                  39
Pune                     34
Gurugram                 32
Hyderabad                29
Delhi NCR                24
Noida                    12
Kolkata                   8
Remote                    7
Ahmedabad                 5
Jaipur                    4
Panaji                    3
Chandigarh                2
Nagpur                    2
Coimbatore                2
Nashik                    1
Nizamabad                 1
Kochi                     1
Indore                    1
Thakurpukur Mahestola     1
Nagercoil                 1
Surat                     1
Palwal                    1
Mohali                    1
Oragadam                  1
Kinshasa                  1
Thane                     1
Bangarapet                1
Hosur                     1
Canada                    1
Tamil nadu                1
Bhubaneshwar              1
Faridabad                 1
Bawal                     1
Sachin                    1
Name: count, dtype: int64

In [152]:
data2.head()

,Unnamed: 0,job_title,company,experience,min exp,max exp,salary,base salary,max salary,location,jobListed(days ago),postedIn,rating,reviews count,details,salary data provide by,Standardize_Job_Title,standard_location
0,1,Data Analyst - Bangalore,Schneider Electric,5-10 Yrs,5.0,10.0,₹ 8 - 16L/yr,800000.0,1600000.0,"Bangalore / Bengaluru, Bangalore Rural",4.0,Naukri,4.2,3500.0,"ERP, SAP, Data Analysis",Salary Listed by Company,Data Analyst,Bengaluru
1,18,Data Analyst,Amazon,2-4 Yrs,2.0,4.0,₹ 1.8 - 7L/yr (AmbitionBox estimate),180000.0,700000.0,"Delhi/Ncr, Bangalore / Bengaluru",11.0,Naukri,4.1,21700.0,"AWS technologies, Excel, SQL",Estimated by Ambition Box,Data Analyst,Delhi NCR
2,26,Specialist - Investments,Jardine Lloyd Thompson India Pvt Ltd.,2-5 Yrs,2.0,5.0,₹ 4.754 - 7L/yr (AmbitionBox estimate),475400.0,700000.0,Pune,3.0,Naukri,4.0,558.0,"Data management, RDBMS, Project management",Estimated by Ambition Box,Other,Pune
3,28,Veeva process specialists,Tech Mahindra,5-10 Yrs,5.0,10.0,₹ 7 - 12L/yr,700000.0,1200000.0,Hyderabad / Secunderabad,3.0,Naukri,3.7,28500.0,"CTMS, CDMS, Veeva",Salary Listed by Company,Other,Hyderabad
4,29,Data Analyst/Sr. Analyst - SAS & Python,FedEx,3-8 Yrs,3.0,8.0,₹ 10 - 20L/yr,1000000.0,2000000.0,"Mumbai, Bangalore / Bengaluru",17.0,Naukri,4.2,1100.0,"Predictive Modeling, Logistic Regression, SAS",Salary Listed by Company,Data Analyst,Mumbai

In [153]:
data

,Job Title,Company Name,Location,Experience Required,Salary,Skills Required,Job Description,Posted Date,Scrape Date,Job Link,Source Platform,Standardized_Job_Title,days_sinced_posted,salary_min,salary_max,salary_avg,Experience_Years
0,Punjabi-Speaking Online Data Analyst,"TELUS International AI Inc. (Las Vegas, United...",Remote,No experience required,"₹ 4,50,000 - 4,60,000","['English Proficiency (Spoken)', 'English Prof...",Are you a detail-oriented individual with a pa...,6 days ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,6.0,450000.0,460000.0,455000.0,0.0
1,Malayalam Language Data Analyst For Online,"TELUS International AI Inc. (Las Vegas, United...",Remote,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analytics'],A Day in the Life of an Online Data Analyst: I...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0,0.0
2,Online Data Analyst – Marathi Speaker,"TELUS International AI Inc. (Las Vegas, United...",Remote,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analytics'],Are you a detail-oriented individual with a pa...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0,0.0
3,Online Data Analyst - Gujarati Language,"TELUS International AI Inc. (Las Vegas, United...",Remote,No experience required,"₹ 4,50,000 - 4,60,000",['Data Analysis'],A Day in the Life of an Online Data Analyst:\r...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0,0.0
4,Remote Online Data Analyst (Urdu-Speaking),"TELUS International AI Inc. (Las Vegas, United...",Remote,No experience required,"₹ 4,50,000 - 4,60,000","['Urdu Proficiency(Spoken)', 'Urdu Proficiency...",Key Responsibilities: \r\n\r\n1. Work on a pro...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-rem...,Internshala,Data Analyst,21.0,450000.0,460000.0,455000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Data Analyst,DECCAN FOUNDERS MEDIA PVT LTD,Hyderabad,1 year(s),"₹ 2,40,000","['Python', 'SQL', 'Statistical Modeling', 'Dat...",Key Responsibilities:\r\n\r\n1. Collect data f...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/data-analys...,Internshala,Data Analyst,21.0,240000.0,240000.0,240000.0,1.0
71,Business Analyst,The Jain Group,Kolkata,1 year(s),"₹ 2,00,000 - 4,00,000","['UI & UX Design', 'Technical Analysis', 'Busi...",Key Responsibilities:\r\n\r\n1. Lead and coord...,1 week ago,2026-04-28,https://internshala.com/job/detail/business-an...,Internshala,Business Analyst,7.0,200000.0,400000.0,300000.0,1.0
72,Data Analytics Executive,Growify Digital,Delhi,1 year(s),"₹ 2,00,000 - 3,00,000","['Data Analytics', 'MS-Excel']",Key responsibilities:\r\n\r\n1. Generating acc...,6 days ago,2026-04-28,https://internshala.com/job/detail/data-analyt...,Internshala,Analytics,6.0,200000.0,300000.0,250000.0,1.0
73,Data Analyst,Avadeti Media (Part Of Ojas Group),Delhi,1 year(s),"₹ 2,00,000 - 3,00,000","['Python', 'SQL', 'Statistical Modeling', 'Bus...",We're Avadeti Media- the narrative intelligenc...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/data-analys...,Internshala,Data Analyst,21.0,200000.0,300000.0,250000.0,1.0
74,Associate Business Analyst,Mobillor Technologies Private Limited,Bangalore,No experience required,"₹ 2,00,000 - 2,50,000","['MS-Office', 'Planning', 'MS-Excel', 'Busines...",1. Understand customer requirements and prepar...,3 weeks ago,2026-04-28,https://internshala.com/job/detail/fresher-ass...,Internshala,Business Analyst,21.0,200000.0,250000.0,225000.0,0.0

In [154]:
data2['salart_avg'] = (data2['base salary'] + data2['max salary']) / 2

In [155]:


def extract_avg_exp(exp):

    if pd.isna(exp):
        return None

    exp = str(exp).lower().strip()

    # extract all numbers
    nums = re.findall(r'\d+', exp)

    if len(nums) >= 2:
        min_exp = int(nums[0])
        max_exp = int(nums[1])

        return (min_exp + max_exp) / 2

    elif len(nums) == 1:
        return int(nums[0])

    return None


data2['avg_experience'] = data2['experience'].apply(extract_avg_exp)

In [156]:
data2[['avg_experience' , 'experience']]

     avg_experience experience
0               7.5   5-10 Yrs
1               3.0    2-4 Yrs
2               3.5    2-5 Yrs
3               7.5   5-10 Yrs
4               5.5    3-8 Yrs
..              ...        ...
338             6.0    4-8 Yrs
339             5.5    3-8 Yrs
340             6.0    4-8 Yrs
341             2.5    2-3 Yrs
342             5.5    3-8 Yrs

[343 rows x 2 columns]

In [157]:
data2.head()

,Unnamed: 0,job_title,company,experience,min exp,max exp,salary,base salary,max salary,location,jobListed(days ago),postedIn,rating,reviews count,details,salary data provide by,Standardize_Job_Title,standard_location,salart_avg,avg_experience
0,1,Data Analyst - Bangalore,Schneider Electric,5-10 Yrs,5.0,10.0,₹ 8 - 16L/yr,800000.0,1600000.0,"Bangalore / Bengaluru, Bangalore Rural",4.0,Naukri,4.2,3500.0,"ERP, SAP, Data Analysis",Salary Listed by Company,Data Analyst,Bengaluru,1200000.0,7.5
1,18,Data Analyst,Amazon,2-4 Yrs,2.0,4.0,₹ 1.8 - 7L/yr (AmbitionBox estimate),180000.0,700000.0,"Delhi/Ncr, Bangalore / Bengaluru",11.0,Naukri,4.1,21700.0,"AWS technologies, Excel, SQL",Estimated by Ambition Box,Data Analyst,Delhi NCR,440000.0,3.0
2,26,Specialist - Investments,Jardine Lloyd Thompson India Pvt Ltd.,2-5 Yrs,2.0,5.0,₹ 4.754 - 7L/yr (AmbitionBox estimate),475400.0,700000.0,Pune,3.0,Naukri,4.0,558.0,"Data management, RDBMS, Project management",Estimated by Ambition Box,Other,Pune,587700.0,3.5
3,28,Veeva process specialists,Tech Mahindra,5-10 Yrs,5.0,10.0,₹ 7 - 12L/yr,700000.0,1200000.0,Hyderabad / Secunderabad,3.0,Naukri,3.7,28500.0,"CTMS, CDMS, Veeva",Salary Listed by Company,Other,Hyderabad,950000.0,7.5
4,29,Data Analyst/Sr. Analyst - SAS & Python,FedEx,3-8 Yrs,3.0,8.0,₹ 10 - 20L/yr,1000000.0,2000000.0,"Mumbai, Bangalore / Bengaluru",17.0,Naukri,4.2,1100.0,"Predictive Modeling, Logistic Regression, SAS",Salary Listed by Company,Data Analyst,Mumbai,1500000.0,5.5

In [158]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salary_avg',
       'remote_status'],
      dtype='object')

In [159]:
data2.columns

Index(['Unnamed: 0', 'job_title', 'company', 'experience', 'min exp',
       'max exp', 'salary', 'base salary', 'max salary', 'location',
       'jobListed(days ago)', 'postedIn', 'rating', 'reviews count', 'details',
       'salary data provide by', 'Standardize_Job_Title', 'standard_location',
       'salart_avg', 'avg_experience'],
      dtype='object')

In [160]:
data2['Skills Required'] = data2['details'].apply(lambda x : x.split(','))

In [161]:
data2['remote_status'] = data2['standard_location'].apply(remote_status)

In [162]:
data2.remote_status.value_counts()

remote_status
0    336
1      7
Name: count, dtype: int64

In [163]:
df2 = data2[['Standardize_Job_Title' , 'avg_experience' , 'standard_location' ,'Skills Required'
             ,'company' ,  'postedIn', 'salart_avg', 'remote_status' ]]

In [164]:
df2.shape

(343, 8)

In [165]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salary_avg',
       'remote_status'],
      dtype='object')

In [166]:
df2 = df2.copy()

In [167]:
df2.rename(columns={
    'Standardize_Job_Title' : 'Standardized_Job_Title',
    'avg_experience' : 'Experience_Years',
    'standard_location' : 'Location',
    'company' :'Company Name',
    'postedIn' : 'Source Platform' 
} , inplace = True)

In [168]:
df2.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,Company Name,Source Platform,salart_avg,remote_status
0,Data Analyst,7.5,Bengaluru,"[ERP, SAP, Data Analysis]",Schneider Electric,Naukri,1200000.0,0
1,Data Analyst,3.0,Delhi NCR,"[AWS technologies, Excel, SQL]",Amazon,Naukri,440000.0,0
2,Other,3.5,Pune,"[Data management, RDBMS, Project management]",Jardine Lloyd Thompson India Pvt Ltd.,Naukri,587700.0,0
3,Other,7.5,Hyderabad,"[CTMS, CDMS, Veeva]",Tech Mahindra,Naukri,950000.0,0
4,Data Analyst,5.5,Mumbai,"[Predictive Modeling, Logistic Regression, SAS]",FedEx,Naukri,1500000.0,0

In [169]:
data3 = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\Salary Prediction Data\final dataset.csv')

In [170]:
data3.head()

,Job_Role,avg_salary,primary_city,is_multi_city,is_remote,city_group,skills,num_skills,experience,has_experience,skill_set
0,Senior Data Scientist,18.9,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
1,Senior Data Scientist,16.7,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
2,Senior Data Scientist,17.9,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
3,Senior Data Scientist,25.6,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
4,Senior Data Scientist,28.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"

In [171]:
data3.shape

(385257, 11)

In [172]:
data3['Standardized_Job_Role'] = data3['Job_Role'].apply(standardize_job_title)

In [173]:
data3.Standardized_Job_Role.value_counts()

Standardized_Job_Role
Data Engineer                145091
Data Scientist               112885
Data Analyst                  78166
Business Analyst              46199
Other                          1500
Machine Learning Engineer      1416
Name: count, dtype: int64

In [174]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385257 entries, 0 to 385256
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Job_Role               385257 non-null  object
 1   avg_salary             385257 non-null  float64
 2   primary_city           385257 non-null  object
 3   is_multi_city          385257 non-null  int64
 4   is_remote              385257 non-null  int64
 5   city_group             385257 non-null  object
 6   skills                 380388 non-null  object
 7   num_skills             385257 non-null  int64
 8   experience             385257 non-null  float64
 9   has_experience         385257 non-null  int64
 10  skill_set              385257 non-null  object
 11  Standardized_Job_Role  385257 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 35.3+ MB

In [175]:
data3.isnull().sum()

Job_Role                    0
avg_salary                  0
primary_city                0
is_multi_city               0
is_remote                   0
city_group                  0
skills                   4869
num_skills                  0
experience                  0
has_experience              0
skill_set                   0
Standardized_Job_Role       0
dtype: int64

In [176]:
data3["skills"] = data3["skills"].fillna("")

In [177]:
data3.isnull().sum()

Job_Role                 0
avg_salary               0
primary_city             0
is_multi_city            0
is_remote                0
city_group               0
skills                   0
num_skills               0
experience               0
has_experience           0
skill_set                0
Standardized_Job_Role    0
dtype: int64

In [178]:
data3["avg_salary"] = (data3["avg_salary"] * 100000).round(2)

In [179]:
data3.describe()

,avg_salary,is_multi_city,is_remote,num_skills,experience,has_experience
count,3.852570e+05,385257.000000,385257.000000,385257.000000,385257.000000,385257.000000
mean,1.197904e+06,0.157277,0.014697,3.384258,5.210278,0.999512
std,6.437660e+05,0.364062,0.120336,1.701759,2.325577,0.022085
min,2.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.300000e+05,0.000000,0.000000,2.000000,3.500000,1.000000
50%,1.080000e+06,0.000000,0.000000,3.000000,5.000000,1.000000
75%,1.530000e+06,0.000000,0.000000,5.000000,6.500000,1.000000
max,3.210000e+06,1.000000,1.000000,9.000000,16.500000,1.000000

In [180]:
data3.head()

,Job_Role,avg_salary,primary_city,is_multi_city,is_remote,city_group,skills,num_skills,experience,has_experience,skill_set,Standardized_Job_Role
0,Senior Data Scientist,1890000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
1,Senior Data Scientist,1670000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
2,Senior Data Scientist,1790000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
3,Senior Data Scientist,2560000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
4,Senior Data Scientist,2800000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist

In [181]:
len(data3['primary_city'].unique().tolist())

63

In [182]:
data3['Location'] = data3['primary_city'].apply(clean_location)

In [183]:
data3.Location.isnull().sum()

np.int64(0)

In [184]:
data3.Location.unique()

array(['Bengaluru', 'Mumbai', 'Gurugram', 'Pune', 'Hyderabad', 'Thane',
       'Chennai', 'Noida', 'Mumbai Suburban', 'Remote', 'Kochi',
       'Kolkata', 'Delhi NCR', 'Lucknow', 'Chandigarh', 'Ahmedabad',
       'Jaipur', 'Kalyani', 'Nagpur', 'Gurgaon', 'Indore', 'Delhi',
       'Bharuch', 'Hosur', 'Panchkula', 'Mohali', 'Guwahati',
       'Thiruvananthapuram', 'Faridabad', 'Uttar Pradesh', 'Panaji',
       'Vadodara', 'Trivandrum', 'Coimbatore', 'Visakhapatnam',
       'Serilingampally', 'Calicut', 'Mangalore', 'Gandhinagar',
       'karnataka', 'Bhopal', 'Madurai', 'Surat', 'Ghaziabad', 'Ambah',
       'Erode', 'Vijayawada', 'Kota', 'Bhiwadi', 'Panjim', 'Gujarat',
       'Muzaffarpur', 'Rajkot', 'Salem', 'Palani', 'punjab'], dtype=object)

In [185]:
len(data3['Location'].unique().tolist())

56

In [186]:
data3.Job_Role.unique()

array(['Senior Data Scientist', 'Data Scientist', 'Senior Data Analyst',
       'Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Data Architect', 'Senior Business Analyst', 'Business Analyst',
       'Machine Learning Engineer'], dtype=object)

In [187]:
data3.columns

Index(['Job_Role', 'avg_salary', 'primary_city', 'is_multi_city', 'is_remote',
       'city_group', 'skills', 'num_skills', 'experience', 'has_experience',
       'skill_set', 'Standardized_Job_Role', 'Location'],
      dtype='object')

In [188]:
data3.shape

(385257, 13)

In [189]:
data3 = data3.drop_duplicates(
    subset=['Job_Role',  'primary_city', 'is_multi_city', 'is_remote',
       'city_group', 'skills', 'num_skills', 'experience', 'has_experience',
       'skill_set', 'Standardized_Job_Role', 'Location'],
    keep='first'
)

In [190]:
data3

,Job_Role,avg_salary,primary_city,is_multi_city,is_remote,city_group,skills,num_skills,experience,has_experience,skill_set,Standardized_Job_Role,Location
0,Senior Data Scientist,1890000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist,Bengaluru
185,Senior Data Scientist,1890000.0,Bangalore/Bengaluru,0,0,metro,"azure, gcp, machine learning, python, r, spark...",7,7.0,1,"{'machine learning', 'azure', 'gcp', 'tensorfl...",Data Scientist,Bengaluru
370,Data Scientist,780000.0,Bangalore/Bengaluru,1,0,metro,"aws, azure, machine learning, python, r",5,2.5,1,"{'machine learning', 'azure', 'aws', 'python',...",Data Scientist,Bengaluru
558,Data Scientist,780000.0,Bangalore/Bengaluru,0,0,metro,"computer vision, deep learning, machine learni...",5,6.0,1,"{'computer vision', 'deep learning', 'machine ...",Data Scientist,Bengaluru
746,Data Scientist,780000.0,Bangalore/Bengaluru,0,0,metro,"agile, cassandra, machine learning, r",4,6.0,1,"{'agile', 'cassandra', 'r', 'machine learning'}",Data Scientist,Bengaluru
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384962,Machine Learning Engineer,580000.0,punjab,0,0,non_metro,"java, machine learning, python, r",4,3.5,1,"{'python', 'r', 'java', 'machine learning'}",Machine Learning Engineer,punjab
385021,Machine Learning Engineer,580000.0,Pune,0,0,metro,"agile, c++, deep learning, keras, machine lear...",8,7.5,1,"{'agile', 'tensorflow', 'c++', 'deep learning'...",Machine Learning Engineer,Pune
385080,Machine Learning Engineer,580000.0,Gurgaon/Gurugram,0,0,metro,"databricks, machine learning, pytorch, r, tens...",5,5.5,1,"{'databricks', 'tensorflow', 'machine learning...",Machine Learning Engineer,Gurugram
385139,Machine Learning Engineer,580000.0,Pune,0,0,metro,"machine learning, python, r",3,6.0,1,"{'python', 'r', 'machine learning'}",Machine Learning Engineer,Pune
385198,Machine Learning Engineer,580000.0,Pune,0,0,metro,"agile, machine learning, python, pytorch, r, s...",6,7.0,1,"{'agile', 'machine learning', 'spark', 'python...",Machine Learning Engineer,Pune

In [191]:
data3 = data3.copy()

In [192]:
data3['Skills Required'] = data3['skills'].apply(lambda x:x.split(','))

In [193]:
data3.head()

,Job_Role,avg_salary,primary_city,is_multi_city,is_remote,city_group,skills,num_skills,experience,has_experience,skill_set,Standardized_Job_Role,Location,Skills Required
0,Senior Data Scientist,1890000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist,Bengaluru,"[machine learning, python, r, scala]"
185,Senior Data Scientist,1890000.0,Bangalore/Bengaluru,0,0,metro,"azure, gcp, machine learning, python, r, spark...",7,7.0,1,"{'machine learning', 'azure', 'gcp', 'tensorfl...",Data Scientist,Bengaluru,"[azure, gcp, machine learning, python, r, ..."
370,Data Scientist,780000.0,Bangalore/Bengaluru,1,0,metro,"aws, azure, machine learning, python, r",5,2.5,1,"{'machine learning', 'azure', 'aws', 'python',...",Data Scientist,Bengaluru,"[aws, azure, machine learning, python, r]"
558,Data Scientist,780000.0,Bangalore/Bengaluru,0,0,metro,"computer vision, deep learning, machine learni...",5,6.0,1,"{'computer vision', 'deep learning', 'machine ...",Data Scientist,Bengaluru,"[computer vision, deep learning, machine lea..."
746,Data Scientist,780000.0,Bangalore/Bengaluru,0,0,metro,"agile, cassandra, machine learning, r",4,6.0,1,"{'agile', 'cassandra', 'r', 'machine learning'}",Data Scientist,Bengaluru,"[agile, cassandra, machine learning, r]"

In [194]:
df2.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salart_avg',
       'remote_status'],
      dtype='object')

In [195]:
data3.columns

Index(['Job_Role', 'avg_salary', 'primary_city', 'is_multi_city', 'is_remote',
       'city_group', 'skills', 'num_skills', 'experience', 'has_experience',
       'skill_set', 'Standardized_Job_Role', 'Location', 'Skills Required'],
      dtype='object')

In [196]:
df3 = data3[['Standardized_Job_Role','experience','Location','Skills Required','avg_salary','is_remote']]

In [197]:
df3.shape

(1995, 6)

In [198]:
df3 = df3.copy()

In [199]:
df3.rename(columns={
    'experience' : 'Experience_Years' , 
    'Standardized_Job_Role' : 'Standardized_Job_Title' , 
    'avg_salary' : 'salary_avg',
    'is_remote' : 'remote_status'

} , inplace  = True)

In [200]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salary_avg',
       'remote_status'],
      dtype='object')

In [201]:
df.drop(
columns=['Company Name', 'Source Platform'], 
axis=1 , inplace = True
)

In [202]:
df2.drop(
   columns=['Company Name', 'Source Platform'], 
axis=1 , inplace= True
)

In [203]:
df2.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salart_avg', 'remote_status'],
      dtype='object')

In [204]:
data4 = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\Salary Prediction Data\job_dataset.csv')

In [205]:
df2.rename(columns={
    'salart_avg' : 'salary_avg' 
} , inplace = True)

In [206]:
df['Skills Required'] = df['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
df2['Skills Required'] = df2['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
df3['Skills Required'] = df3['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)

In [207]:
df = df.merge(df2 , how = 'outer' , on = ['Standardized_Job_Title' , 'Experience_Years' , 'Location' , 'Skills Required' , 'salary_avg' , 'remote_status'])

In [208]:
df3.rename(columns={
    'salart_avg' : 'salary_avg'
} , inplace = True)

In [209]:
df = df.merge(df3 , how = 'outer' , on = ['Standardized_Job_Title' , 'Experience_Years' , 'Location' , 'Skills Required' , 'salary_avg' , 'remote_status'])

In [210]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Data Engineer                747
Data Analyst                 729
Data Scientist               580
Business Analyst             245
Other                         68
Machine Learning Engineer     26
Analytics                     18
Name: count, dtype: int64

In [211]:
df = df[df['Standardized_Job_Title'] != 'Other'].copy()

In [212]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Data Engineer                747
Data Analyst                 729
Data Scientist               580
Business Analyst             245
Machine Learning Engineer     26
Analytics                     18
Name: count, dtype: int64

In [213]:
df.shape

(2345, 6)

In [214]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import re


#Scrapping Data from the Internshala Job portal
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "en-US,en;q=0.9"
}
for j in range(1,16):
    url = f"https://www.ambitionbox.com/jobs/data-analyst-jobs-prf"
    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
    except requests.exceptions.Timeout:
        print("Request timed out")
    except requests.exceptions.RequestException as e:
        print("Request failed:", e)
    soup = BeautifulSoup(response.text , "html.parser")

In [215]:
job_titles = []
locations = []
salary = []
experience_list = []
skills_required= []

In [216]:
cards = soup.find_all("div", class_="jobInfoCard")

for card in cards:

    # TITLE
    title_tag = card.find("a", class_="title noclick")
    title = title_tag.text.strip() if title_tag else None

    # EXPERIENCE
    exp_div = card.find(
        "div",
        title=lambda x: x and "year" in x.lower()
    )

    experience = (
        exp_div.find("p").text.strip()
        if exp_div and exp_div.find("p")
        else None
    )

    # LOCATION
    loc_div = card.find(
        "div",
        class_=lambda x: x and "loc" in x
    )

    location = (
        loc_div.find("p").text.strip()
        if loc_div and loc_div.find("p")
        else None
    )

    # SALARY
    salary_icon = card.find(
        "div",
        title=lambda x: x and "L/yr" in x
    )

    salary = (
        salary_icon.find_next("p").text.strip()
        if salary_icon
        else None
    )

    

    print(title, experience, location, salary)

Data Analyst - Fixed Term Contract 1-3 Yrs Mumbai None
S&C Global Network - AI - Data Strategy - Analyst 2-5 Yrs Gurugram ₹ 4.3L/yr - 14L/yr (AmbitionBox estimate)
Data Analyst 5-7 Yrs Hybrid · Hyderabad ₹ 8L/yr - 18L/yr
Data Analyst 4-7 Yrs Hyderabad ₹ 8L/yr - 16L/yr
Opening For Data Analyst | ETL | Informatica - Hyderabad 3-5 Yrs Hyderabad ₹ 3L/yr - 10L/yr (AmbitionBox estimate)
Opening For Data Analyst | ETL | Informatica - Hyderabad 5-8 Yrs Hyderabad None
Data Analyst-ETL | data warehousing| data modeling - Hyderabad 3-5 Yrs Hyderabad ₹ 3L/yr - 10L/yr (AmbitionBox estimate)
Data Analyst-ETL | data warehousing| data modeling - Hyderabad 5-8 Yrs Hyderabad None
SC S4 Data Readiness Analyst - Contract 4-8 Yrs Chennai ₹ 3.5L/yr - 10L/yr (AmbitionBox estimate)
S&C Global Network - AI - Data Strategy - Analyst 2-5 Yrs Bengaluru ₹ 3.4L/yr - 12L/yr (AmbitionBox estimate)
DEM Analyst 2-4 Yrs Pune ₹ 3L/yr - 4.5L/yr (AmbitionBox estimate)
Data Analysts (ETL, SQL, Informatica)-Hyderabad Location 5-8 Yrs Hybrid · Hyderabad None
Data Analysts(ETL, SQL, Informatica)-Hyderabad Location 3-5 Yrs Hybrid · Hyderabad ₹ 3L/yr - 16L/yr (AmbitionBox estimate)
Data Analyst 4-8 Yrs Bengaluru None
Opening For Data Analyst | ETL | Informatica - Hyderaad 3-8 Yrs Hyderabad None
Data Analyst - Immediate 3-6 Yrs Chennai None
Data Analyst - Post Market Surveillance 5-10 Yrs Bengaluru None
Analyst, Logistics & Material Management 4-9 Yrs Pune None
Opening For Data Analyst | ETL | Informatica - Hyderaad 3-8 Yrs Hyderabad None
Data Analyst (SQL, Informatica) s 5-8 Yrs Hybrid · Hyderabad None

In [228]:
skill_divs = soup.find_all(
    "div",
    title=True
)

for div in skill_divs:

    title = div.get("title")

    # skills usually contain commas
    if title and "," in title:
        skills = list(title.split(","))

['Power BI', ' Data Analysis', ' SQL', ' Tableau', ' Marketing Analytics', ' Revenue Management', ' Pricing', ' Insights', ' Predictive Analytics', ' Predictive Modeling']
['Data Analytics', ' Supply Chain Management', ' Machine Learning', ' Analytics', ' Natural Language Processing', ' Deep Learning', ' Data Governance', ' Data Quality']
['Data Analytics', ' Python', ' SQL']
['Power BI', ' Data Analysis', ' Python', ' SQL', ' Tableau']
['Informatica', ' ETL', ' Data Warehousing', ' Data Modeling', ' Data Integration', ' Data Quality', ' Data Pipeline']
['Informatica', ' ETL', ' Data Warehousing', ' Data Modeling', ' Data Integration', ' Data Quality', ' Data Pipeline']
['Informatica', ' ETL', ' Iics']
['Informatica', ' ETL', ' Iics']
['Pharmacy', ' Recruitment', ' Supply Chain', ' Risk Management', ' ERP', ' FMCG Sales', ' Data Structures', ' Data Migration', ' Data Quality']
['Data Analysis', ' Data Analytics', ' SQL', ' Artificial Intelligence', ' Machine Learning', ' Procurement', ' Amadeus', ' Business Development', ' Deep Learning', ' Reservation', ' Ticketing', ' IT Services', ' Strategic Sourcing', ' Holiday Packages', ' International Ticketing']
['Customer Service', ' Proof Reading', ' User Experience Design', ' UX', ' Analytics', ' RPA', ' Incident Management', ' Automation', ' Powershell', ' Service Delivery']
['Data Analysts (ETL', ' SQL', ' Informatica)-Hyderabad Location']
['Data Analytics', ' SQL', ' Informatica', ' ETL']
['Data Analysts(ETL', ' SQL', ' Informatica)-Hyderabad Location']
['Data Analytics', ' SQL', ' Informatica', ' ETL']
['Power BI', ' Data Analytics', ' SQL', ' Tableau', ' Data Visualization', ' Master Data Management', ' Communication Skills', ' Data Modeling']
['Informatica', ' ETL', ' Iics']
['Data Analysis', ' SQL', ' Data Visualization']
['Data Analysis', ' SQL', ' Healthcare', ' Operations', ' Data Mining', ' Business Intelligence', ' Analytical', ' Data Modeling', ' Data Quality']
['Analyst', ' Logistics & Material Management']
['SAP', ' Data Analysis', ' Logistics', ' Supply Chain Management', ' SQL', ' Analytics', ' Automation', ' ERP', ' Material Management', ' Data Quality']
['Informatica', ' ETL', ' Iics']
['Data Analyst (SQL', ' Informatica) s']
['Data Analysis', ' Data Analytics', ' SQL', ' Informatica', ' ETL', ' Powercenter']

In [238]:
def scrape_data(role, num_pages=1, base_url="https://www.ambitionbox.com/jobs"):
    """Scrape job listings for a given role and return a dataframe.

    role: string like 'data-analyst', 'data scientist', or 'machine-learning-engineer'
    num_pages: number of pagination pages to scrape
    """
    def normalize_role(role_text):
        text = str(role_text).strip().lower()
        return text.replace(" ", "-").replace("/", "-").replace("_", "-")

    role_slug = normalize_role(role)
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept-Language": "en-US,en;q=0.9"
    }

    rows = []

    for page in range(1, num_pages + 1):
        url = f"{base_url}/{role_slug}-jobs-prf?page={page}"
        try:
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status()
        except requests.exceptions.Timeout:
            print(f"Page {page}: request timed out for role {role}")
            continue
        except requests.exceptions.RequestException as e:
            print(f"Page {page}: request failed for role {role}: {e}")
            continue

        soup = BeautifulSoup(response.text, "html.parser")
        cards = soup.find_all("div", class_=lambda x: x and "jobInfoCard" in x)

        if not cards:
            print(f"Page {page}: no job cards found for role {role} using URL {url}")

        for card in cards:
            title_tag = card.find("a", class_=lambda x: x and "title" in x)
            title = title_tag.text.strip() if title_tag else None

            exp_div = card.find("div", title=lambda x: x and "year" in x.lower())
            experience = exp_div.find("p").text.strip() if exp_div and exp_div.find("p") else None

            loc_div = card.find("div", class_=lambda x: x and "loc" in x)
            location = loc_div.find("p").text.strip() if loc_div and loc_div.find("p") else None

            salary_div = card.find("div", title=lambda x: x and "L/yr" in x)
            salary = salary_div.find_next("p").text.strip() if salary_div else None

            skill_divs = soup.find_all(
            "div",
            title=True
            )
            for div in skill_divs:
                title = div.get("title")
            # skills usually contain commas
                if title and "," in title:
                    skills = list(title.split(","))

        rows.append({
                "Role": role,
                "Job Title": title,
                "Experience": experience,
                "Location": location,
                "Salary": salary,
                "Skills": skills
            })

            # Extract skills from page-level divs with title attribute containing commas
        



    return pd.DataFrame(rows)


def scrape_roles(roles, num_pages=1):
    """Scrape multiple roles and return a dict of dataframes."""
    return {role: scrape_data(role, num_pages=num_pages) for role in roles}

In [239]:
scrape_data("data analyst", num_pages=2)

,Role,Job Title,Experience,Location,Salary,Skills
0,data analyst,Enter a Company or Designation,5-8 Yrs,Hyderabad,None,"[Data Analysis, Data Analytics, SQL, Inform..."
1,data analyst,Enter a Company or Designation,8-10 Yrs,Hyderabad,None,"[Data Analysis, Data Analytics, SQL, FRD, ..."

In [245]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "en-US,en;q=0.9"
}


def scrape_jobs(role, pages):

    all_jobs = []

    # convert role to url format
    role_url = role.lower().replace(" ", "-")

    for page in range(1, pages + 1):

        url = f"https://www.ambitionbox.com/jobs/{role_url}-jobs-prf?page={page}"

        print(f"Scraping Page {page}")

        try:
            response = requests.get(
                url,
                headers=headers,
                timeout=10
            )

            response.raise_for_status()

        except requests.exceptions.Timeout:
            print("Request timed out")
            continue

        except requests.exceptions.RequestException as e:
            print("Request failed:", e)
            continue

        soup = BeautifulSoup(response.text, "html.parser")

        cards = soup.find_all("div", class_="jobInfoCard")

        for card in cards:

            # TITLE
            title_tag = card.find("a", class_="title noclick")

            job_title = (
                title_tag.text.strip()
                if title_tag else None
            )

            # EXPERIENCE
            exp_div = card.find(
                "div",
                title=lambda x: x and "year" in x.lower()
            )

            experience = (
                exp_div.get("title")
                if exp_div else None
            )

            # LOCATION
            loc_div = card.find(
                "div",
                class_=lambda x: x and "loc" in x
            )

            location = (
                loc_div.get("title")
                if loc_div else None
            )

            # SALARY
            salary_div = card.find(
                "div",
                title=lambda x: x and "L/yr" in x
            )

            salary = (
                salary_div.get("title")
                if salary_div else None
            )

            # SKILLS
            skills = None

            skill_divs = card.find_all("div", title=True)

            for div in skill_divs:

                skill_title = div.get("title")

                # skills usually contain commas
                if skill_title and "," in skill_title:

                    skills = [
                        skill.strip()
                        for skill in skill_title.split(",")
                    ]

                    break

            # STORE DATA
            all_jobs.append({
                "role": role,
                "job_title": job_title,
                "experience": experience,
                "location": location,
                "salary": salary,
                "skills": skills
            })

    # dataframe
    df = pd.DataFrame(all_jobs)

    return df

In [246]:
da_df = scrape_jobs("data analyst"  , 2)

Scraping Page 1
Scraping Page 2

In [247]:
da_df

,role,job_title,experience,location,salary,skills
0,data analyst,Data Analyst - Fixed Term Contract,1-3 years,Mumbai,None,"[Power BI, Data Analysis, SQL, Tableau, Market..."
1,data analyst,S&C Global Network - AI - Data Strategy - Analyst,2-5 years,Gurugram,₹ 4.3L/yr - 14L/yr,"[Data Analytics, Supply Chain Management, Mach..."
2,data analyst,Data Analyst,5-7 years,Hyderabad,₹ 8L/yr - 18L/yr,"[Data Analytics, Python, SQL]"
3,data analyst,Data Analyst,4-7 years,Hyderabad,₹ 8L/yr - 16L/yr,"[Power BI, Data Analysis, Python, SQL, Tableau]"
4,data analyst,Opening For Data Analyst | ETL | Informatica -...,3-5 years,Hyderabad,₹ 3L/yr - 10L/yr,"[Informatica, ETL, Data Warehousing, Data Mode..."
5,data analyst,Opening For Data Analyst | ETL | Informatica -...,5-8 years,Hyderabad,None,"[Informatica, ETL, Data Warehousing, Data Mode..."
6,data analyst,Data Analyst-ETL | data warehousing| data mode...,3-5 years,Hyderabad,₹ 3L/yr - 10L/yr,"[Informatica, ETL, Iics]"
7,data analyst,Data Analyst-ETL | data warehousing| data mode...,5-8 years,Hyderabad,None,"[Informatica, ETL, Iics]"
8,data analyst,SC S4 Data Readiness Analyst - Contract,4-8 years,Chennai,₹ 3.5L/yr - 10L/yr,"[Pharmacy, Recruitment, Supply Chain, Risk Man..."
9,data analyst,S&C Global Network - AI - Data Strategy - Analyst,2-5 years,Bengaluru,₹ 3.4L/yr - 12L/yr,"[Data Analysis, Data Analytics, SQL, Artificia..."
10,data analyst,DEM Analyst,2-4 years,Pune,₹ 3L/yr - 4.5L/yr,"[Customer Service, Proof Reading, User Experie..."
11,data analyst,"Data Analysts (ETL, SQL, Informatica)-Hyderaba...",5-8 years,Hyderabad,None,"[Data Analytics, SQL, Informatica, ETL]"
12,data analyst,"Data Analysts(ETL, SQL, Informatica)-Hyderabad...",3-5 years,Hyderabad,₹ 3L/yr - 16L/yr,"[Data Analytics, SQL, Informatica, ETL]"
13,data analyst,Data Analyst,4-8 years,Bengaluru,None,"[Power BI, Data Analytics, SQL, Tableau, Data ..."
14,data analyst,Opening For Data Analyst | ETL | Informatica -...,3-8 years,Hyderabad,None,"[Informatica, ETL, Iics]"
15,data analyst,Data Analyst - Immediate,3-6 years,Chennai,None,"[Data Analysis, SQL, Data Visualization]"
16,data analyst,Data Analyst - Post Market Surveillance,5-10 years,Bengaluru,None,"[Data Analysis, SQL, Healthcare, Operations, D..."
17,data analyst,"Analyst, Logistics & Material Management",4-9 years,Pune,None,"[SAP, Data Analysis, Logistics, Supply Chain M..."
18,data analyst,Opening For Data Analyst | ETL | Informatica -...,3-8 years,Hyderabad,None,"[Informatica, ETL, Iics]"
19,data analyst,"Data Analyst (SQL, Informatica) s",5-8 years,Hyderabad,None,"[Data Analysis, Data Analytics, SQL, Informati..."
20,data analyst,"Analyst, Logistics & Material Management",4-9 years,Pune,None,"[SAP, Data Analysis, Logistics, Supply Chain M..."
21,data analyst,Opening For Data Analyst | ETL | Informatica -...,3-8 years,Hyderabad,None,"[Informatica, ETL, Iics]"
22,data analyst,Data Analyst,4-8 years,"Pune, Bengaluru",₹ 25L/yr - 40L/yr,"[Pune, Bengaluru]"
23,data analyst,"Data Analyst (SQL, Informatica) s",5-8 years,Hyderabad,None,"[Data Analysis, Data Analytics, SQL, Informati..."
24,data analyst,Data Analyst,1-2 years,Pune,₹ 2.5L/yr - 13L/yr,"[Data Science, Data Engineering, SQL, Cloud Se..."
25,data analyst,Data Analyst,3-5 years,Bengaluru,₹ 0.5L/yr - 0.8L/yr,"[Power BI, Python, SQL, Tableau, Google Analyt..."
26,data analyst,Data Analyst/ Data Modeler,13-16 years,"Hyderabad, Pune, Delhi/Ncr",None,"[Hyderabad, Pune, Delhi/Ncr]"
27,data analyst,Data Analyst,5-7 years,Bengaluru,None,"[Power BI, SQL, Advanced Excel]"
28,data analyst,Opening For Data Analyst | ETL | Informatica -...,3-8 years,Hyderabad,None,"[Informatica, ETL, Iics]"
29,data analyst,GN-Chemicals&Natural Resources-Data AI-Analyst,3-5 years,Bengaluru,₹ 2.6L/yr - 13.5L/yr,"[Python, Sales, Supply Chain Management, SQL, ..."
30,data analyst,"Consultant, Data Analytics & Reporting - Ag & ...",5-10 years,Bengaluru,None,"[Power BI, SAP, Data Analysis, Data Analytics,..."
31,data analyst,Data Analyst - Ethics & compliance,4-5 years,Pune,₹ 6.1L/yr - 19L/yr,"[Data Analysis, Performance Management]"
32,data analyst,Analyst – Data & Insights III,5-10 years,Bengaluru,₹ 6L/yr - 10.1L/yr,"[Power BI, Marketing, Data Analytics, Salesfor..."
33,data analyst,Data Analyst,3-5 years,Chennai,₹ 9L/yr - 17.5L/yr,"[SAP, Data Analysis, Supply Chain Management, ..."
34,data analyst,Data BA,10-15 years,"Mumbai, Hyderabad, Bengaluru",None,"[Mumbai, Hyderabad, Bengaluru]"
35,data analyst,Data Analyst,4-9 years,"Chennai, Delhi/Ncr, Mumbai",None,"[Chennai, Delhi/Ncr, Mumbai]"
36,data analyst,Diageo - Manager - Data Analysis (8-12 yrs),8-12 years,Bengaluru,None,"[Data Analytics, Statistics, Analytics, Data M..."
37,data analyst,Packaging Data Analyst,3-5 years,Gurugram,None,"[SAP, Supply Chain, ERP, Assurance, Operationa..."
38,data analyst,Data Analyst,3-7 years,Hyderabad,None,"[Python, SQL]"
39,data analyst,Data Analyst,8-10 years,Hyderabad,None,"[Data Analysis, Data Analytics, SQL, FRD, Data..."

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   role                    900 non-null    object
 1   job_title               753 non-null    object
 2   experience              894 non-null    object
 3   location                894 non-null    object
 4   salary                  268 non-null    object
 5   skills                  865 non-null    object
 6   Standardized_Job_Title  900 non-null    object
 7   avg_experience          894 non-null    float64
 8   avg_salary              268 non-null    float64
dtypes: float64(2), object(7)
memory usage: 63.4+ KB