In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\processed\salary_jobs.csv')

In [3]:
data.columns

Index(['Job Title', 'Company Name', 'Location', 'Experience Required',
       'Salary', 'Skills Required', 'Job Description', 'Posted Date',
       'Scrape Date', 'Job Link', 'Source Platform', 'Standardized_Job_Title',
       'days_sinced_posted', 'salary_min', 'salary_max', 'salary_avg',
       'Experience_Years'],
      dtype='object')

In [4]:
df = data[['Standardized_Job_Title' , 'Experience_Years' , 'Location' , 'Skills Required' 
           , 'Company Name' , 'Source Platform' , 'salary_avg']]

In [5]:
df.shape

(75, 7)

In [6]:
df

,Standardized_Job_Title,Experience_Years,Location,Skills Required,Company Name,Source Platform,salary_avg
0,Data Analyst,0.0,Remote,"['English Proficiency (Spoken)', 'English Prof...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
1,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
2,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
3,Data Analyst,0.0,Remote,['Data Analysis'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
4,Data Analyst,0.0,Remote,"['Urdu Proficiency(Spoken)', 'Urdu Proficiency...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0
...,...,...,...,...,...,...,...
70,Data Analyst,1.0,Hyderabad,"['Python', 'SQL', 'Statistical Modeling', 'Dat...",DECCAN FOUNDERS MEDIA PVT LTD,Internshala,240000.0
71,Business Analyst,1.0,Kolkata,"['UI & UX Design', 'Technical Analysis', 'Busi...",The Jain Group,Internshala,300000.0
72,Analytics,1.0,Delhi,"['Data Analytics', 'MS-Excel']",Growify Digital,Internshala,250000.0
73,Data Analyst,1.0,Delhi,"['Python', 'SQL', 'Statistical Modeling', 'Bus...",Avadeti Media (Part Of Ojas Group),Internshala,250000.0
74,Business Analyst,0.0,Bangalore,"['MS-Office', 'Planning', 'MS-Excel', 'Busines...",Mobillor Technologies Private Limited,Internshala,225000.0

In [7]:
def remote_status(location):
    if r'Remote' in location:
        return 1
    else:
        return 0

In [8]:
df =df.copy()

In [9]:
df['remote_status'] = df['Location'].apply(remote_status)

In [10]:
df.remote_status.value_counts()

remote_status
1    44
0    31
Name: count, dtype: int64

In [11]:
df.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,Company Name,Source Platform,salary_avg,remote_status
0,Data Analyst,0.0,Remote,"['English Proficiency (Spoken)', 'English Prof...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
1,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
2,Data Analyst,0.0,Remote,['Data Analytics'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
3,Data Analyst,0.0,Remote,['Data Analysis'],"TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1
4,Data Analyst,0.0,Remote,"['Urdu Proficiency(Spoken)', 'Urdu Proficiency...","TELUS International AI Inc. (Las Vegas, United...",Internshala,455000.0,1

In [12]:
data2 = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\Salary Prediction Data\dataAnalystJobsIndia.csv')

In [13]:
data2.head()

,Unnamed: 0,job_title,company,experience,min exp,max exp,salary,base salary,max salary,location,jobListed(days ago),postedIn,rating,reviews count,details,salary data provide by
0,0,JP Morgan Chase - Client Data Analyst (4-8 yrs),JP Morgan Chase,4-8 Yrs,4.0,8.0,NaN,NaN,NaN,Hyderabad / Secunderabad,3.0,iimjobs,4.1,5300.0,"Banking, KYC, Banking Operations",NaN
1,1,Data Analyst - Bangalore,Schneider Electric,5-10 Yrs,5.0,10.0,₹ 8 - 16L/yr,800000.0,1600000.0,"Bangalore / Bengaluru, Bangalore Rural",4.0,Naukri,4.2,3500.0,"ERP, SAP, Data Analysis",Salary Listed by Company
2,2,Senior IT ATLAS Data Analyst and Integration S...,SAP Labs India Pvt. Ltd.,7-11 Yrs,7.0,11.0,NaN,NaN,NaN,Bangalore / Bengaluru,7.0,Naukri,4.3,1500.0,"data quality, Data analysis, quality management",NaN
3,3,Consultant Data Analyst,Pfizer,2-6 Yrs,2.0,6.0,NaN,NaN,NaN,Mumbai,3.0,Naukri,4.1,1700.0,"Power Bi, Commercial Operations, Data Management",NaN
4,4,Senior Data Analyst - Retail Liabilities,IDFC FIRST Bank,5-10 Yrs,5.0,10.0,NaN,NaN,NaN,Mumbai,5.0,Naukri,4.5,2300.0,"Test strategy, Analytical, Manager Technology",NaN

In [14]:
data2.isnull().sum()

Unnamed: 0                   0
job_title                    0
company                      0
experience                  34
min exp                     34
max exp                     34
salary                    1218
base salary               1218
max salary                1218
location                    33
jobListed(days ago)          0
postedIn                     0
rating                     437
reviews count              437
details                     33
salary data provide by    1218
dtype: int64

In [15]:
data2 = data2[data2['base salary'].notnull()].copy()
data2.reset_index(drop=True , inplace=True)

In [16]:
data2.shape

(343, 16)

In [17]:
def standardize_job_title(title):
    title = str(title).lower()

    if "data analyst" in title:
        return "Data Analyst"
    elif "data scientist" in title:
        return "Data Scientist"
    elif "business analyst" in title:
        return "Business Analyst"
    elif "machine learning" in title:
        return "Machine Learning Engineer"
    elif "data engineer" in title:
        return "Data Engineer"
    elif "product analyst" in title:
        return "Product Analyst"
    elif "analytics" in title:
        return "Analytics"
    else:
        return "Other"

In [18]:

data2['Standardize_Job_Title'] = data2['job_title'].apply(standardize_job_title)

location cleaning

In [19]:
import re

In [20]:
def clean_location(location):

    if pd.isna(location):
        return "Unknown"

    location = str(location)

    # remove +more
    location = re.sub(r"\+.*more", "", location)

    # remove tabs/newlines
    location = re.sub(r"\s+", " ", location).strip()

    # split multi-city
    location = location.split(",")[0].strip()

    # mapping
    location_map = {

        "Bangalore / Bengaluru": "Bengaluru",
        "Bengaluru/Bangalore": "Bengaluru",
        "Bangalore Rural": "Bengaluru",
        "Bangalore/Bengaluru": "Bengaluru",

        "Mohali/SAS Nagar" : "Mohali" ,

        "Trivandrum/Thiruvananthapuram" : "Thiruvananthapuram" ,

        "Delhi/Ncr": "Delhi NCR",
        "New Delhi": "Delhi NCR",
        "Delhi / NCR": "Delhi NCR",

        "Gurgaon / Gurugram": "Gurugram",
        "Gurgaon/Gurugram": "Gurugram",

        "Mumbai suburbs": "Mumbai",
        "Mumbai Suburbs": "Mumbai",
        "Navi Mumbai": "Mumbai",

        "Hyderabad / Secunderabad": "Hyderabad",
        "Hyderabad/Secunderabad": "Hyderabad",

        "Mangaluru/Mangalore" : "Mangalore" , 

        "Panaji/Panjim" : "Panaji" ,

        "Calicut/Kozhikode" : "Calicut" , 

        "Kochi/Cochin" : "Kochi" ,
        "Cochin/Ernakulam/Kochi" : "Kochi",

        "Remote": "Remote",

        "India": "Remote"
    }

    return location_map.get(location, location)

In [21]:
data2["standard_location"] = data2["location"].apply(clean_location)

In [22]:
data2.standard_location.value_counts()

standard_location
Bengaluru                72
Mumbai                   48
Chennai                  39
Pune                     34
Gurugram                 32
Hyderabad                29
Delhi NCR                24
Noida                    12
Kolkata                   8
Remote                    7
Ahmedabad                 5
Jaipur                    4
Panaji                    3
Chandigarh                2
Nagpur                    2
Coimbatore                2
Nashik                    1
Nizamabad                 1
Kochi                     1
Indore                    1
Thakurpukur Mahestola     1
Nagercoil                 1
Surat                     1
Palwal                    1
Mohali                    1
Oragadam                  1
Kinshasa                  1
Thane                     1
Bangarapet                1
Hosur                     1
Canada                    1
Tamil nadu                1
Bhubaneshwar              1
Faridabad                 1
Bawal                     1
Sachin                    1
Name: count, dtype: int64

In [23]:
data2.head()

,Unnamed: 0,job_title,company,experience,min exp,max exp,salary,base salary,max salary,location,jobListed(days ago),postedIn,rating,reviews count,details,salary data provide by,Standardize_Job_Title,standard_location
0,1,Data Analyst - Bangalore,Schneider Electric,5-10 Yrs,5.0,10.0,₹ 8 - 16L/yr,800000.0,1600000.0,"Bangalore / Bengaluru, Bangalore Rural",4.0,Naukri,4.2,3500.0,"ERP, SAP, Data Analysis",Salary Listed by Company,Data Analyst,Bengaluru
1,18,Data Analyst,Amazon,2-4 Yrs,2.0,4.0,₹ 1.8 - 7L/yr (AmbitionBox estimate),180000.0,700000.0,"Delhi/Ncr, Bangalore / Bengaluru",11.0,Naukri,4.1,21700.0,"AWS technologies, Excel, SQL",Estimated by Ambition Box,Data Analyst,Delhi NCR
2,26,Specialist - Investments,Jardine Lloyd Thompson India Pvt Ltd.,2-5 Yrs,2.0,5.0,₹ 4.754 - 7L/yr (AmbitionBox estimate),475400.0,700000.0,Pune,3.0,Naukri,4.0,558.0,"Data management, RDBMS, Project management",Estimated by Ambition Box,Other,Pune
3,28,Veeva process specialists,Tech Mahindra,5-10 Yrs,5.0,10.0,₹ 7 - 12L/yr,700000.0,1200000.0,Hyderabad / Secunderabad,3.0,Naukri,3.7,28500.0,"CTMS, CDMS, Veeva",Salary Listed by Company,Other,Hyderabad
4,29,Data Analyst/Sr. Analyst - SAS & Python,FedEx,3-8 Yrs,3.0,8.0,₹ 10 - 20L/yr,1000000.0,2000000.0,"Mumbai, Bangalore / Bengaluru",17.0,Naukri,4.2,1100.0,"Predictive Modeling, Logistic Regression, SAS",Salary Listed by Company,Data Analyst,Mumbai

In [24]:
data2['salart_avg'] = (data2['base salary'] + data2['max salary']) / 2

In [25]:


def extract_avg_exp(exp):

    if pd.isna(exp):
        return None

    exp = str(exp).lower().strip()

    # extract all numbers
    nums = re.findall(r'\d+', exp)

    if len(nums) >= 2:
        min_exp = int(nums[0])
        max_exp = int(nums[1])

        return (min_exp + max_exp) / 2

    elif len(nums) == 1:
        return int(nums[0])

    return None


data2['avg_experience'] = data2['experience'].apply(extract_avg_exp)

In [26]:
data2[['avg_experience' , 'experience']]

     avg_experience experience
0               7.5   5-10 Yrs
1               3.0    2-4 Yrs
2               3.5    2-5 Yrs
3               7.5   5-10 Yrs
4               5.5    3-8 Yrs
..              ...        ...
338             6.0    4-8 Yrs
339             5.5    3-8 Yrs
340             6.0    4-8 Yrs
341             2.5    2-3 Yrs
342             5.5    3-8 Yrs

[343 rows x 2 columns]

In [27]:
data2.head()

,Unnamed: 0,job_title,company,experience,min exp,max exp,salary,base salary,max salary,location,jobListed(days ago),postedIn,rating,reviews count,details,salary data provide by,Standardize_Job_Title,standard_location,salart_avg,avg_experience
0,1,Data Analyst - Bangalore,Schneider Electric,5-10 Yrs,5.0,10.0,₹ 8 - 16L/yr,800000.0,1600000.0,"Bangalore / Bengaluru, Bangalore Rural",4.0,Naukri,4.2,3500.0,"ERP, SAP, Data Analysis",Salary Listed by Company,Data Analyst,Bengaluru,1200000.0,7.5
1,18,Data Analyst,Amazon,2-4 Yrs,2.0,4.0,₹ 1.8 - 7L/yr (AmbitionBox estimate),180000.0,700000.0,"Delhi/Ncr, Bangalore / Bengaluru",11.0,Naukri,4.1,21700.0,"AWS technologies, Excel, SQL",Estimated by Ambition Box,Data Analyst,Delhi NCR,440000.0,3.0
2,26,Specialist - Investments,Jardine Lloyd Thompson India Pvt Ltd.,2-5 Yrs,2.0,5.0,₹ 4.754 - 7L/yr (AmbitionBox estimate),475400.0,700000.0,Pune,3.0,Naukri,4.0,558.0,"Data management, RDBMS, Project management",Estimated by Ambition Box,Other,Pune,587700.0,3.5
3,28,Veeva process specialists,Tech Mahindra,5-10 Yrs,5.0,10.0,₹ 7 - 12L/yr,700000.0,1200000.0,Hyderabad / Secunderabad,3.0,Naukri,3.7,28500.0,"CTMS, CDMS, Veeva",Salary Listed by Company,Other,Hyderabad,950000.0,7.5
4,29,Data Analyst/Sr. Analyst - SAS & Python,FedEx,3-8 Yrs,3.0,8.0,₹ 10 - 20L/yr,1000000.0,2000000.0,"Mumbai, Bangalore / Bengaluru",17.0,Naukri,4.2,1100.0,"Predictive Modeling, Logistic Regression, SAS",Salary Listed by Company,Data Analyst,Mumbai,1500000.0,5.5

In [28]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salary_avg',
       'remote_status'],
      dtype='object')

In [29]:
data2.columns

Index(['Unnamed: 0', 'job_title', 'company', 'experience', 'min exp',
       'max exp', 'salary', 'base salary', 'max salary', 'location',
       'jobListed(days ago)', 'postedIn', 'rating', 'reviews count', 'details',
       'salary data provide by', 'Standardize_Job_Title', 'standard_location',
       'salart_avg', 'avg_experience'],
      dtype='object')

In [30]:
data2['Skills Required'] = data2['details'].apply(lambda x : x.split(','))

In [31]:
data2['remote_status'] = data2['standard_location'].apply(remote_status)

In [32]:
data2.remote_status.value_counts()

remote_status
0    336
1      7
Name: count, dtype: int64

In [33]:
df2 = data2[['Standardize_Job_Title' , 'avg_experience' , 'standard_location' ,'Skills Required'
             ,'company' ,  'postedIn', 'salart_avg', 'remote_status' ]]

In [34]:
df2.shape

(343, 8)

In [35]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salary_avg',
       'remote_status'],
      dtype='object')

In [36]:
df2 = df2.copy()

In [37]:
df2.rename(columns={
    'Standardize_Job_Title' : 'Standardized_Job_Title',
    'avg_experience' : 'Experience_Years',
    'standard_location' : 'Location',
    'company' :'Company Name',
    'postedIn' : 'Source Platform' 
} , inplace = True)

In [38]:
df2.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,Company Name,Source Platform,salart_avg,remote_status
0,Data Analyst,7.5,Bengaluru,"[ERP, SAP, Data Analysis]",Schneider Electric,Naukri,1200000.0,0
1,Data Analyst,3.0,Delhi NCR,"[AWS technologies, Excel, SQL]",Amazon,Naukri,440000.0,0
2,Other,3.5,Pune,"[Data management, RDBMS, Project management]",Jardine Lloyd Thompson India Pvt Ltd.,Naukri,587700.0,0
3,Other,7.5,Hyderabad,"[CTMS, CDMS, Veeva]",Tech Mahindra,Naukri,950000.0,0
4,Data Analyst,5.5,Mumbai,"[Predictive Modeling, Logistic Regression, SAS]",FedEx,Naukri,1500000.0,0

In [39]:
data3 = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\Salary Prediction Data\final dataset.csv')

In [40]:
data3.head()

,Job_Role,avg_salary,primary_city,is_multi_city,is_remote,city_group,skills,num_skills,experience,has_experience,skill_set
0,Senior Data Scientist,18.9,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
1,Senior Data Scientist,16.7,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
2,Senior Data Scientist,17.9,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
3,Senior Data Scientist,25.6,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"
4,Senior Data Scientist,28.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}"

In [41]:
data3.shape

(385257, 11)

In [42]:
data3['Standardized_Job_Role'] = data3['Job_Role'].apply(standardize_job_title)

In [43]:
data3.Standardized_Job_Role.value_counts()

Standardized_Job_Role
Data Engineer                145091
Data Scientist               112885
Data Analyst                  78166
Business Analyst              46199
Other                          1500
Machine Learning Engineer      1416
Name: count, dtype: int64

In [44]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385257 entries, 0 to 385256
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Job_Role               385257 non-null  object
 1   avg_salary             385257 non-null  float64
 2   primary_city           385257 non-null  object
 3   is_multi_city          385257 non-null  int64
 4   is_remote              385257 non-null  int64
 5   city_group             385257 non-null  object
 6   skills                 380388 non-null  object
 7   num_skills             385257 non-null  int64
 8   experience             385257 non-null  float64
 9   has_experience         385257 non-null  int64
 10  skill_set              385257 non-null  object
 11  Standardized_Job_Role  385257 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 35.3+ MB

In [45]:
data3.isnull().sum()

Job_Role                    0
avg_salary                  0
primary_city                0
is_multi_city               0
is_remote                   0
city_group                  0
skills                   4869
num_skills                  0
experience                  0
has_experience              0
skill_set                   0
Standardized_Job_Role       0
dtype: int64

In [46]:
data3["skills"] = data3["skills"].fillna("")

In [47]:
data3.isnull().sum()

Job_Role                 0
avg_salary               0
primary_city             0
is_multi_city            0
is_remote                0
city_group               0
skills                   0
num_skills               0
experience               0
has_experience           0
skill_set                0
Standardized_Job_Role    0
dtype: int64

In [48]:
data3["avg_salary"] = (data3["avg_salary"] * 100000).round(2)

In [49]:
data3.describe()

,avg_salary,is_multi_city,is_remote,num_skills,experience,has_experience
count,3.852570e+05,385257.000000,385257.000000,385257.000000,385257.000000,385257.000000
mean,1.197904e+06,0.157277,0.014697,3.384258,5.210278,0.999512
std,6.437660e+05,0.364062,0.120336,1.701759,2.325577,0.022085
min,2.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.300000e+05,0.000000,0.000000,2.000000,3.500000,1.000000
50%,1.080000e+06,0.000000,0.000000,3.000000,5.000000,1.000000
75%,1.530000e+06,0.000000,0.000000,5.000000,6.500000,1.000000
max,3.210000e+06,1.000000,1.000000,9.000000,16.500000,1.000000

In [50]:
data3.head()

,Job_Role,avg_salary,primary_city,is_multi_city,is_remote,city_group,skills,num_skills,experience,has_experience,skill_set,Standardized_Job_Role
0,Senior Data Scientist,1890000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
1,Senior Data Scientist,1670000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
2,Senior Data Scientist,1790000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
3,Senior Data Scientist,2560000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist
4,Senior Data Scientist,2800000.0,Bangalore/Bengaluru,1,0,metro,"machine learning, python, r, scala",4,4.5,1,"{'python', 'scala', 'r', 'machine learning'}",Data Scientist

In [51]:
len(data3['primary_city'].unique().tolist())

63

In [52]:
data3['Location'] = data3['primary_city'].apply(clean_location)

In [53]:
data3.Location.isnull().sum()

np.int64(0)

In [54]:
data3.Location.unique()

array(['Bengaluru', 'Mumbai', 'Gurugram', 'Pune', 'Hyderabad', 'Thane',
       'Chennai', 'Noida', 'Mumbai Suburban', 'Remote', 'Kochi',
       'Kolkata', 'Delhi NCR', 'Lucknow', 'Chandigarh', 'Ahmedabad',
       'Jaipur', 'Kalyani', 'Nagpur', 'Gurgaon', 'Indore', 'Delhi',
       'Bharuch', 'Hosur', 'Panchkula', 'Mohali', 'Guwahati',
       'Thiruvananthapuram', 'Faridabad', 'Uttar Pradesh', 'Panaji',
       'Vadodara', 'Trivandrum', 'Coimbatore', 'Visakhapatnam',
       'Serilingampally', 'Calicut', 'Mangalore', 'Gandhinagar',
       'karnataka', 'Bhopal', 'Madurai', 'Surat', 'Ghaziabad', 'Ambah',
       'Erode', 'Vijayawada', 'Kota', 'Bhiwadi', 'Panjim', 'Gujarat',
       'Muzaffarpur', 'Rajkot', 'Salem', 'Palani', 'punjab'], dtype=object)

In [55]:
len(data3['Location'].unique().tolist())

56

In [56]:
data3.Job_Role.unique()

array(['Senior Data Scientist', 'Data Scientist', 'Senior Data Analyst',
       'Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Data Architect', 'Senior Business Analyst', 'Business Analyst',
       'Machine Learning Engineer'], dtype=object)

In [57]:
data3.columns

Index(['Job_Role', 'avg_salary', 'primary_city', 'is_multi_city', 'is_remote',
       'city_group', 'skills', 'num_skills', 'experience', 'has_experience',
       'skill_set', 'Standardized_Job_Role', 'Location'],
      dtype='object')

In [58]:
data3.shape

(385257, 13)

In [59]:
data3 = data3.drop_duplicates(
    subset=['Job_Role',  'primary_city', 'is_multi_city', 'is_remote',
       'city_group', 'skills', 'num_skills', 'experience', 'has_experience',
       'skill_set', 'Standardized_Job_Role', 'Location'],
    keep='first'
)

In [60]:
data3 = data3.copy()

In [61]:
data3['Skills Required'] = data3['skills'].apply(lambda x:x.split(','))

In [62]:
df2.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salart_avg',
       'remote_status'],
      dtype='object')

In [63]:
data3.columns

Index(['Job_Role', 'avg_salary', 'primary_city', 'is_multi_city', 'is_remote',
       'city_group', 'skills', 'num_skills', 'experience', 'has_experience',
       'skill_set', 'Standardized_Job_Role', 'Location', 'Skills Required'],
      dtype='object')

In [64]:
df3 = data3[['Standardized_Job_Role','experience','Location','Skills Required','avg_salary','is_remote']]

In [65]:
df3.shape

(1995, 6)

In [66]:
df3 = df3.copy()

In [67]:
df3.rename(columns={
    'experience' : 'Experience_Years' , 
    'Standardized_Job_Role' : 'Standardized_Job_Title' , 
    'avg_salary' : 'salary_avg',
    'is_remote' : 'remote_status'

} , inplace  = True)

In [68]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'Company Name', 'Source Platform', 'salary_avg',
       'remote_status'],
      dtype='object')

In [69]:
df.drop(
columns=['Company Name', 'Source Platform'], 
axis=1 , inplace = True
)

In [70]:
df2.drop(
   columns=['Company Name', 'Source Platform'], 
axis=1 , inplace= True
)

In [71]:
df2.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salart_avg', 'remote_status'],
      dtype='object')

In [72]:
data4 = pd.read_csv(r'd:\Startup\Project\ai-career-coach\data\Salary Prediction Data\job_dataset.csv')

In [73]:
df2.rename(columns={
    'salart_avg' : 'salary_avg' 
} , inplace = True)

In [74]:
df['Skills Required'] = df['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
df2['Skills Required'] = df2['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
df3['Skills Required'] = df3['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)

In [75]:
df = pd.concat([df ,df2 ], ignore_index=True)

In [76]:
df3.rename(columns={
    'salart_avg' : 'salary_avg'
} , inplace = True)

In [77]:
df = pd.concat([df ,df3] , ignore_index=True)

In [78]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Data Engineer                747
Data Analyst                 729
Data Scientist               580
Business Analyst             245
Other                         68
Machine Learning Engineer     26
Analytics                     18
Name: count, dtype: int64

In [79]:
df = df[df['Standardized_Job_Title'] != 'Other'].copy()

In [80]:
df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Data Engineer                747
Data Analyst                 729
Data Scientist               580
Business Analyst             245
Machine Learning Engineer     26
Analytics                     18
Name: count, dtype: int64

In [81]:
df.shape

(2345, 6)

In [82]:
da_df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\Salary Prediction Data\data_analyst_jobs.csv")
ds_df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\Salary Prediction Data\data_scientist_jobs.csv")
de_df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\Salary Prediction Data\data_engineer_jobs.csv")
ml_df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\Salary Prediction Data\ml_engineer_jobs.csv")
ba_df = pd.read_csv(r"d:\Startup\Project\ai-career-coach\data\Salary Prediction Data\business_analyst_jobs.csv")

In [83]:
da_df.isnull().sum()

role                        0
job_title                 147
experience                  6
location                    6
salary                    632
skills                     35
Standardized_Job_Title      0
avg_experience              6
avg_salary                632
dtype: int64

In [84]:
ds_df.isnull().sum()

role                        0
job_title                  96
experience                  2
location                   10
salary                    799
skills                     16
Standardized_Job_Title      0
avg_experience              2
avg_salary                799
dtype: int64

In [85]:
de_df.isnull().sum()

role                         0
job_title                    0
experience                   1
location                     4
salary                    1021
skills                       2
Standardized_Job_Title       0
avg_experience               1
avg_salary                1021
dtype: int64

In [86]:
ml_df.isnull().sum()

role                        0
job_title                  67
experience                  0
location                    7
salary                    356
skills                      5
Standardized_Job_Title      0
avg_experience              0
avg_salary                356
dtype: int64

In [87]:
ba_df.isnull().sum()

role                        0
job_title                   0
experience                  0
location                    2
salary                    524
skills                     20
Standardized_Job_Title      0
avg_experience              0
avg_salary                524
dtype: int64

In [88]:
da_df.columns

Index(['role', 'job_title', 'experience', 'location', 'salary', 'skills',
       'Standardized_Job_Title', 'avg_experience', 'avg_salary'],
      dtype='object')

In [89]:
master_df = pd.concat([da_df ,ds_df] , ignore_index=True)

In [90]:
master_df = pd.concat([master_df ,de_df ], ignore_index=True)
master_df = pd.concat([master_df ,ml_df ], ignore_index=True)
master_df = pd.concat([master_df ,ba_df ], ignore_index=True)

In [91]:
master_df.sample(5)

,role,job_title,experience,location,salary,skills,Standardized_Job_Title,avg_experience,avg_salary
3930,business analyst,Business Analyst,2-7 years,Gurugram,NaN,"['Power BI', 'Data Analytics', 'Accounting', '...",Business Analyst,4.5,NaN
4141,business analyst,Business Analyst -Regulatory Reporting (MNC BANK),6-11 years,Goregaon,₹ 15L/yr - 30L/yr,"['SEBI', 'Regulatory Reporting', 'Business Ana...",Business Analyst,8.5,2250000.0
2532,data engineer,Data Engineer,6-11 years,Mumbai,₹ 14L/yr - 24L/yr,"['GCP', 'Hadoop', 'Hive']",Data Engineer,8.5,1900000.0
1003,data scientist,Data Scientist-Artificial Intelligence,8-10 years,Bengaluru,₹ 18L/yr - 36.5L/yr,"['Python', 'AWS', 'Supply Chain Management', '...",Data Scientist,9.0,2700000.0
2557,data engineer,DBT Data Engineer,5-10 years,"Pune, Chennai, Bengaluru",NaN,"['Pune', 'Chennai', 'Bengaluru']",Data Engineer,7.5,NaN

In [92]:
master_df.shape

(4514, 9)

In [93]:
master_df.isnull().sum()

role                         0
job_title                  310
experience                   9
location                    29
salary                    3332
skills                      78
Standardized_Job_Title       0
avg_experience               9
avg_salary                3332
dtype: int64

In [94]:
master_df = master_df[master_df['salary'].notnull()].copy()

In [95]:
master_df['location'] = master_df['location'].apply(clean_location)

In [96]:
master_df.location.unique()

array(['Gurugram', 'Hyderabad', 'Chennai', 'Bengaluru', 'Pune', 'Mumbai',
       'Delhi NCR', 'Noida', 'Nagpur', 'Mumbai Suburban', 'Remote',
       'Indore', 'Ahmedabad', 'Gandhinagar', 'Vadodara', 'Ernakulam',
       'Vijayawada', 'Kolkata', 'Surat', 'Coimbatore', 'Jaipur',
       'South Goa', 'Sahibzada Ajit Singh Nagar', 'Pimpri-Chinchwad',
       'Thane', 'Madurai', 'Kochi', 'Bidar', 'Nandyal', 'Kanchipuram',
       'Kota', 'Thiruvananthapuram', 'Singapore', 'Dubai',
       'United arab emirates', 'Sholinganallur', 'Bhubaneswar',
       'Visakhapatnam', 'Malad', 'Lucknow', 'Ambattur', 'Mysuru',
       'Goregaon', 'Dahej', 'Patna', 'Raipur', 'Ghaziabad', 'Chandigarh',
       'Malappuram'], dtype=object)

In [97]:
master_df['remote_status'] = master_df['location'].apply(remote_status)

In [98]:
master_df.columns

Index(['role', 'job_title', 'experience', 'location', 'salary', 'skills',
       'Standardized_Job_Title', 'avg_experience', 'avg_salary',
       'remote_status'],
      dtype='object')

In [99]:
master_df.shape

(1182, 10)

In [100]:
master_df.rename(columns={
    'Standardized_Job_Title' : 'role',
    'role' : 'Standardized_Job_Title' ,
    'avg_experience' : 'Experience_Years',
    'location' : 'Location' , 
    'skills' : 'Skills Required' , 
    'avg_salary' : 'salary_avg' 
} , inplace= True)

In [101]:
master_scrape_df = master_df[['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salary_avg', 'remote_status']]

In [102]:
master_scrape_df.shape

(1182, 6)

In [103]:
master_scrape_df.Standardized_Job_Title.value_counts().sum()

np.int64(1182)

In [104]:
df[df['Standardized_Job_Title'] == 'Data Analyst'].sample(5)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
168,Data Analyst,0.5,Chennai,"Pivot Table, Communication Skills, VLOOKUP",150000.0,0
365,Data Analyst,4.5,Gurugram,"Data Analyst, professional",930000.0,0
183,Data Analyst,2.0,Coimbatore,"Dax Queries, Power Bi Reports, Business Intell...",500000.0,0
1587,Data Analyst,2.5,Delhi NCR,python,470000.0,0
104,Data Analyst,7.5,Chennai,"tableau, Power BI, Data Analytics",1250000.0,0

In [105]:
master_scrape_df = master_scrape_df.copy()

In [106]:
master_scrape_df['Standardized_Job_Title'] = master_scrape_df['Standardized_Job_Title'].str.title()

In [107]:
master_scrape_df['Skills Required'] = master_scrape_df['Skills Required'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)

In [108]:
df.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salary_avg', 'remote_status'],
      dtype='object')

In [109]:
master_salary_data = pd.concat([master_scrape_df ,df ], ignore_index=True)

In [110]:
master_salary_data.shape

(3527, 6)

In [111]:
master_salary_data.sample(15)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
283,Data Scientist,7.0,Bengaluru,"['SAP', 'Python', 'SQL', 'Mining Engineering',...",1050000.0,0
87,Data Analyst,3.0,Hyderabad,"['Power BI', 'Python', 'AWS', 'SQL']",500000.0,0
2492,Data Engineer,5.5,Hyderabad,"r, sql",1100000.0,0
665,Data Engineer,3.0,Mumbai,"['Data Engineering', 'Python', 'SQL', 'Oracle'...",1100000.0,0
330,Data Scientist,4.5,Hyderabad,"['Hyderabad', 'Gurugram', 'Bengaluru']",1500000.0,0
1542,Data Analyst,4.5,Bengaluru,"SQL, Data analysis, Consulting",4875000.0,0
2261,Data Analyst,3.0,Chennai,"r, ssis, ssrs",990000.0,0
3492,Business Analyst,2.5,Mumbai,"nosql, r, sql",690000.0,0
479,Data Engineer,6.5,Bengaluru,"['Data Engineering', 'Supply Chain Management'...",550000.0,0
3196,Data Engineer,5.0,Hyderabad,"azure, kubernetes, r",580000.0,0
2231,Data Analyst,2.5,Bengaluru,"java, javascript, r",470000.0,0
721,Data Engineer,3.0,Bengaluru,"['Data Engineering', 'Supply Chain Management'...",450000.0,0
1324,Data Analyst,1.5,Mumbai,"Formulas, Advanced Excel, Calculation",187500.0,0
1061,Business Analyst,4.5,Bengaluru,"['Data Analysis', 'Operations', 'Auditing', 'D...",300000.0,0
2570,Data Analyst,3.0,Mumbai,"management, r",470000.0,0

In [112]:
from pathlib import Path
BASE_PATH = Path(r"d:\Startup\Project\ai-career-coach\data")
SALARY_DATA_PATH = BASE_PATH / "Salary Prediction Data"

final_train_data = pd.read_csv(BASE_PATH / SALARY_DATA_PATH / "Final_Train_Dataset.csv")
final_test_data = pd.read_csv(BASE_PATH / SALARY_DATA_PATH / "Final_Test_Dataset.csv")

final_df = pd.concat([final_train_data , final_test_data] , ignore_index=True)

In [113]:
master_salary_data.columns

Index(['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salary_avg', 'remote_status'],
      dtype='object')

In [114]:
final_df['Standardized_Job_Title'] = final_df['job_desig'].apply(standardize_job_title)

In [115]:
final_df.Standardized_Job_Title.value_counts()

Standardized_Job_Title
Other                        20840
Analytics                     2679
Business Analyst              1321
Data Scientist                 613
Data Analyst                   450
Machine Learning Engineer      291
Data Engineer                  183
Product Analyst                 26
Name: count, dtype: int64

In [116]:

final_df = final_df[final_df['Standardized_Job_Title'] != 'Other'].copy()

In [117]:
import os
import sys
PROJECT_ROOT = Path(r"d:\Startup\Project\ai-career-coach\src\scraper\Salary_data_scrape.py").resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))
from src.scraper.Salary_data_scrape import extract_avg_salary

In [118]:
final_df['salary_avg'] = final_df['salary'].apply(extract_avg_salary)

In [119]:
final_df['Experience_Years'] = final_df['experience'].apply(extract_avg_exp)

In [120]:
final_df.head()

,Unnamed: 0,experience,job_description,job_desig,job_type,key_skills,location,salary,company_name_encoded,Standardized_Job_Title,salary_avg,Experience_Years
3,3.0,7-10 yrs,7 - 10 years of overall experience in data e...,Associate Manager Data Engineering,Analytics,"SQL, Javascript, Automation, Python, Ruby, Ana...",Bengaluru,10to15,313,Data Engineer,1250000.0,8.5
6,6.0,13-15 yrs,- Experience in managing fraud analytics with ...,Associate Vice President - Fraud Analytics - S...,Analytics,"Fraud Analytics, People Management Skills, Tea...",Delhi NCR,25to50,1988,Analytics,3750000.0,14.0
10,10.0,3-7 yrs,Manage large volumes of structured and unstruc...,Business Analyst,NaN,"Test Data, Data Science, Business Analysis, Ma...",Mohali,6to10,3492,Business Analyst,800000.0,5.0
12,12.0,2-6 yrs,3+ years of software development experience;Le...,Sales and Marketing Data Analyst - Data Analytics,Analytics,"Marketing Automation, Sales, Salesforce, Eloqu...",Pune(Kharadi),10to15,3692,Data Analyst,1250000.0,4.0
13,13.0,2-4 yrs,- Knowledge of big data concepts and hands-on ...,Analytics Specialist - Data Science & Big Data,Analytics,"Data Science, Machine Learning, R, Big Data, P...",Mumbai,6to10,4479,Analytics,800000.0,3.0

In [121]:
final_df['location'] = final_df['location'].apply(clean_location)

In [122]:
import re

In [123]:

final_df['location'] = final_df['location'].str.replace(r'\s*\([^)]*\)', '', regex=True).str.strip()

In [124]:
final_df['remote_status'] = final_df['location'].apply(remote_status)

In [125]:
final_df['Skills Required'] = final_df['key_skills'].astype(str).str.replace(r'\.{3,}$', '', regex=True).str.strip()

In [126]:
final_df.dtypes

Unnamed: 0                float64
experience                 object
job_description            object
job_desig                  object
job_type                   object
key_skills                 object
location                   object
salary                     object
company_name_encoded        int64
Standardized_Job_Title     object
salary_avg                float64
Experience_Years          float64
remote_status               int64
Skills Required            object
dtype: object

In [127]:
final_df['Skills Required'] = (
    final_df['Skills Required']
      .fillna('')
      .astype(str)
      .str.split(',')
      .apply(lambda items: [x.strip() for x in items if x.strip()])
)

In [128]:
final_df.reset_index(
    drop = True , 
    inplace = True
)

In [129]:
print(final_df.loc[0, 'Skills Required'])

['SQL', 'Javascript', 'Automation', 'Python', 'Ruby', 'Analytics', 'Machine learning']

In [130]:
final_df.rename(columns= {
    'location' : 'Location'
} , inplace = True)

In [131]:
master_final_df = final_df[['Standardized_Job_Title', 'Experience_Years', 'Location',
       'Skills Required', 'salary_avg', 'remote_status']]

In [132]:
master_final_df.shape

(5563, 6)

In [133]:
master_final_df.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
0,Data Engineer,8.5,Bengaluru,"[SQL, Javascript, Automation, Python, Ruby, An...",1250000.0,0
1,Analytics,14.0,Delhi NCR,"[Fraud Analytics, People Management Skills, Te...",3750000.0,0
2,Business Analyst,5.0,Mohali,"[Test Data, Data Science, Business Analysis, M...",800000.0,0
3,Data Analyst,4.0,Pune,"[Marketing Automation, Sales, Salesforce, Eloq...",1250000.0,0
4,Analytics,3.0,Mumbai,"[Data Science, Machine Learning, R, Big Data, ...",800000.0,0

In [134]:
salary_final_data = pd.concat([master_salary_data , master_final_df] , ignore_index=True)

In [135]:
salary_final_data.sample(5)

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
3372,Business Analyst,2.5,Mumbai,r,690000.0,0
5556,Analytics,9.5,Gurgaon,"[insurance analytics, sas, team leading, life ...",2000000.0,0
8281,Analytics,6.0,Bengaluru,"[Accounting, Hana, ABAP, Rice]",NaN,0
1547,Data Analyst,3.0,Nagpur,"Help Desk, Customer Service, data analysis",370000.0,0
7840,Data Analyst,0.5,Mumbai,"[Data Analyst, PV Case Processing, Pharmacovig...",NaN,0

In [136]:
salary_final_data.head()

,Standardized_Job_Title,Experience_Years,Location,Skills Required,salary_avg,remote_status
0,Data Analyst,3.5,Gurugram,"['Data Analytics', 'Supply Chain Management', ...",350000.0,0
1,Data Analyst,6.0,Hyderabad,"['Data Analytics', 'Python', 'SQL']",1300000.0,0
2,Data Analyst,5.5,Hyderabad,"['Power BI', 'Data Analysis', 'Python', 'SQL',...",1200000.0,0
3,Data Analyst,4.0,Hyderabad,"['Informatica', 'ETL', 'Data Warehousing', 'Da...",650000.0,0
4,Data Analyst,4.0,Hyderabad,"['Informatica', 'ETL', 'Iics']",650000.0,0

In [137]:
salary_final_data.isnull().sum()

Standardized_Job_Title       0
Experience_Years             9
Location                     0
Skills Required             16
salary_avg                1410
remote_status                0
dtype: int64

In [138]:
salary_final_data['Skills Required'] = (
    salary_final_data['Skills Required']
      .astype(str)
      .str.split(',')
      .apply(lambda items: [x.strip() for x in items if x.strip()])
)

In [139]:
def flatten_nested_list(item):
    """Flatten nested lists in Skills Required column"""
    if isinstance(item, list):
        result = []
        for element in item:
            if isinstance(element, list):
                result.extend(element)
            else:
                result.append(element)
        return result
    return item

# Apply the flattening function to Skills Required column
salary_final_data['Skills Required'] = salary_final_data['Skills Required'].apply(flatten_nested_list)

In [140]:
def flatten_nested_list(item):
    """Flatten nested lists in Skills Required column"""
    if isinstance(item, list):
        result = []
        for element in item:
            if isinstance(element, list):
                result.extend(element)
            else:
                result.append(element)
        return result
    return item

# Apply the flattening function to Skills Required column
salary_final_data['Skills Required'] = salary_final_data['Skills Required'].apply(flatten_nested_list)

In [141]:
# Verify the flattening worked - check a sample
salary_final_data[['Standardized_Job_Title', 'Skills Required']].head(10)

  Standardized_Job_Title                                    Skills Required
0           Data Analyst  [['Data Analytics', 'Supply Chain Management',...
1           Data Analyst              [['Data Analytics', 'Python', 'SQL']]
2           Data Analyst  [['Power BI', 'Data Analysis', 'Python', 'SQL'...
3           Data Analyst  [['Informatica', 'ETL', 'Data Warehousing', 'D...
4           Data Analyst                   [['Informatica', 'ETL', 'Iics']]
5           Data Analyst  [['Pharmacy', 'Recruitment', 'Supply Chain', '...
6           Data Analyst  [['Data Analysis', 'Data Analytics', 'SQL', 'A...
7           Data Analyst  [['Customer Service', 'Proof Reading', 'User E...
8           Data Analyst  [['Data Analytics', 'SQL', 'Informatica', 'ETL']]
9           Data Analyst                            [['Pune', 'Bengaluru']]

In [142]:
def flatten_nested_list_v2(item):
    """Recursively flatten nested lists"""
    if not isinstance(item, list):
        return item
    
    result = []
    for element in item:
        if isinstance(element, list):
            # Recursively flatten nested lists
            flattened = flatten_nested_list_v2(element)
            if isinstance(flattened, list):
                result.extend(flattened)
            else:
                result.append(flattened)
        else:
            result.append(element)
    return result

# Apply the improved flattening function
salary_final_data['Skills Required'] = salary_final_data['Skills Required'].apply(flatten_nested_list_v2)

# Verify the result
print("Sample after flattening:")
print(salary_final_data[['Standardized_Job_Title', 'Skills Required']].head(10))

Sample after flattening:
  Standardized_Job_Title                                    Skills Required
0           Data Analyst  [['Data Analytics', 'Supply Chain Management',...
1           Data Analyst              [['Data Analytics', 'Python', 'SQL']]
2           Data Analyst  [['Power BI', 'Data Analysis', 'Python', 'SQL'...
3           Data Analyst  [['Informatica', 'ETL', 'Data Warehousing', 'D...
4           Data Analyst                   [['Informatica', 'ETL', 'Iics']]
5           Data Analyst  [['Pharmacy', 'Recruitment', 'Supply Chain', '...
6           Data Analyst  [['Data Analysis', 'Data Analytics', 'SQL', 'A...
7           Data Analyst  [['Customer Service', 'Proof Reading', 'User E...
8           Data Analyst  [['Data Analytics', 'SQL', 'Informatica', 'ETL']]
9           Data Analyst                            [['Pune', 'Bengaluru']]

In [143]:
# Check the actual type and content
print("Type of first element:", type(salary_final_data['Skills Required'].iloc[0]))
print("First element:", salary_final_data['Skills Required'].iloc[0])
print("\nFirst element repr:", repr(salary_final_data['Skills Required'].iloc[0]))

# Check if they're strings or actual lists
print("\nAre these strings?", isinstance(salary_final_data['Skills Required'].iloc[0], str))

Type of first element: <class 'list'>
First element: ["['Data Analytics'", "'Supply Chain Management'", "'Machine Learning'", "'Analytics'", "'Natural Language Processing'", "'Deep Learning'", "'Data Governance'", "'Data Quality']"]

First element repr: ["['Data Analytics'", "'Supply Chain Management'", "'Machine Learning'", "'Analytics'", "'Natural Language Processing'", "'Deep Learning'", "'Data Governance'", "'Data Quality']"]

Are these strings? False

In [144]:
import ast

def clean_skills_column(item):
    """Clean and flatten the Skills Required column"""
    if not isinstance(item, list):
        return item
    
    result = []
    for element in item:
        if isinstance(element, str):
            # Remove leading/trailing brackets and quotes
            cleaned = element.strip()
            if cleaned.startswith("["):
                try:
                    # Try to parse as a list
                    parsed = ast.literal_eval(cleaned)
                    if isinstance(parsed, list):
                        result.extend(parsed)
                    else:
                        result.append(parsed)
                except:
                    # If parsing fails, clean up quotes and add
                    cleaned = cleaned.strip("'\"[]")
                    if cleaned:
                        result.append(cleaned)
            else:
                # Remove quotes and add
                cleaned = cleaned.strip("'\"")
                if cleaned:
                    result.append(cleaned)
        elif isinstance(element, list):
            result.extend(element)
        else:
            result.append(element)
    
    return result

# Apply the cleaning function
salary_final_data['Skills Required'] = salary_final_data['Skills Required'].apply(clean_skills_column)

# Verify the result
print("Sample after cleaning:")
print(salary_final_data[['Standardized_Job_Title', 'Skills Required']].head(10))

Sample after cleaning:
  Standardized_Job_Title                                    Skills Required
0           Data Analyst  [Data Analytics, Supply Chain Management, Mach...
1           Data Analyst                    [Data Analytics, Python, SQL']]
2           Data Analyst  [Power BI, Data Analysis, Python, SQL, Tableau']]
3           Data Analyst  [Informatica, ETL, Data Warehousing, Data Mode...
4           Data Analyst                         [Informatica, ETL, Iics']]
5           Data Analyst  [Pharmacy, Recruitment, Supply Chain, Risk Man...
6           Data Analyst  [Data Analysis, Data Analytics, SQL, Artificia...
7           Data Analyst  [Customer Service, Proof Reading, User Experie...
8           Data Analyst          [Data Analytics, SQL, Informatica, ETL']]
9           Data Analyst                                [Pune, Bengaluru']]

In [145]:
import re

def clean_skills_final(item):
    """Final cleaning of Skills Required column - handles all edge cases"""
    if not isinstance(item, list):
        return item
    
    result = []
    for element in item:
        if isinstance(element, str):
            # Remove all leading/trailing quotes, brackets, and spaces
            cleaned = element.strip().strip("'\"[]()").strip()
            if cleaned:
                result.append(cleaned)
        elif isinstance(element, list):
            # Recursively handle nested lists
            nested_result = clean_skills_final(element)
            if isinstance(nested_result, list):
                result.extend(nested_result)
            else:
                result.append(nested_result)
        else:
            result.append(element)
    
    return result

# Apply the final cleaning function
salary_final_data['Skills Required'] = salary_final_data['Skills Required'].apply(clean_skills_final)

# Verify the result
print("Sample after final cleaning:")
for i in range(min(5, len(salary_final_data))):
    print(f"Row {i}: {salary_final_data['Skills Required'].iloc[i][:3]}...")  # Show first 3 skills
    
print("\nFull samples:")
print(salary_final_data[['Standardized_Job_Title', 'Skills Required']].head(10))

Sample after final cleaning:
Row 0: ['Data Analytics', 'Supply Chain Management', 'Machine Learning']...
Row 1: ['Data Analytics', 'Python', 'SQL']...
Row 2: ['Power BI', 'Data Analysis', 'Python']...
Row 3: ['Informatica', 'ETL', 'Data Warehousing']...
Row 4: ['Informatica', 'ETL', 'Iics']...

Full samples:
  Standardized_Job_Title                                    Skills Required
0           Data Analyst  [Data Analytics, Supply Chain Management, Mach...
1           Data Analyst                      [Data Analytics, Python, SQL]
2           Data Analyst    [Power BI, Data Analysis, Python, SQL, Tableau]
3           Data Analyst  [Informatica, ETL, Data Warehousing, Data Mode...
4           Data Analyst                           [Informatica, ETL, Iics]
5           Data Analyst  [Pharmacy, Recruitment, Supply Chain, Risk Man...
6           Data Analyst  [Data Analysis, Data Analytics, SQL, Artificia...
7           Data Analyst  [Customer Service, Proof Reading, User Experie...
8           Data Analyst            [Data Analytics, SQL, Informatica, ETL]
9           Data Analyst                                  [Pune, Bengaluru]

In [146]:
# Final verification - check all values are proper lists with no nested lists
print("Verification Results:")
print(f"Total rows: {len(salary_final_data)}")
print(f"All values are lists: {salary_final_data['Skills Required'].apply(lambda x: isinstance(x, list)).all()}")
print(f"No empty lists: {(salary_final_data['Skills Required'].apply(len) > 0).all()}")

# Check for any remaining nested lists
has_nested = salary_final_data['Skills Required'].apply(
    lambda x: any(isinstance(item, list) for item in x) if isinstance(x, list) else False
).any()
print(f"No nested lists found: {not has_nested}")

# Show statistics
print(f"\nSkills count statistics:")
print(salary_final_data['Skills Required'].apply(len).describe())

Verification Results:
Total rows: 9090
All values are lists: True
No empty lists: False
No nested lists found: True

Skills count statistics:
count    9090.000000
mean        5.083718
std         3.051278
min         0.000000
25%         3.000000
50%         5.000000
75%         6.000000
max        30.000000
Name: Skills Required, dtype: float64

In [147]:
salary_final_data.to_csv(BASE_PATH / SALARY_DATA_PATH / "salary_final_data.csv")